### PR TITLE
[WIPTEST]Test infra and cloud vm retirement

### PR DESCRIPTION
**Pull request by akarol**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ea133ad7ad1fe44f18230cab7568ba97351ff2c0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@akarol I will need to rebase this as you modified the instance.py file.

**Comment by akarol** [comment]
Too many conflicts to resolve  which was taking more time then expected so have opened  new PR https://github.com/RedHatQE/cfme_tests/pull/2662 for the same and will close this.

**Pull request closed without merging**
