### PR TITLE
artifactor plugin: always assume we have a valid item.location

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this is a experiment to see why the workaround was added to begin with

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3e6535b7e00f2a5e72f8f6e35a3e62d2757ede04:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Needs signing

**Comment by dajoRH** [comment]
Lint report for commit 2b9f1a37c6225271283728730ef87ea96c57b525:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Looks good and the 54 failure was not related - @mfalesni what you think, should we merge and "see" if it breaks?

**Comment by mfalesni** [comment]
@psav Yeah, let's merge it.

**Pull request merged**
