### PR TITLE
Fix for default view in toolbar

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/configure/test_default_views_cloud.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 5e4dd87a0d1e3f0d7d87dd28cb74efe143cfebc6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
@lehinevych I didn't see you had put this up and started working on #2401. This is good, but I think there was some other stuff that was not addressed by it, which I _think_ I added in. We will see when the PRT run finishes.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by lehinevych** [comment]
Closing in favor of #2401

**Pull request closed without merging**
