### PR TITLE
Test cloud exists and details mode

### PR DESCRIPTION
**Pull request by akarol**
{{pytest: -v -k 'test_details_view or test_exists_view'}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b3f701ccc0e73c07692c814f09ef8cec637d28e6:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/configure/test_default_views_cloud.py:189:50: W292 no newline at end of file
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6c24550da3a911f8e06c2a5add3e8670518ab370:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
The PR tester indicates some locator issues.

**Comment by dajoRH** [comment]
Lint report for commit 1398cfd6a1f40796e06f3755ab571aeac34a727e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2024804cb70bab211e8c77328a39dcb5c9adc1f1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
