### PR TITLE
[WIP][NO TEST] Sprout - description field for pools

### PR DESCRIPTION
**Pull request by mfalesni**
Fully functional for pools, not functioning for the appliances alone yet.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2043daab7344111eb4a1a9f3d25cb44deaba81b1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1a875b20c8463a3ac8b2d2d2f136fa7ce4daea3d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
I was hoping to use something like (but maybe not exactly this) this to initiate cleanups in jenkins. Mainly, if jenkins is requesting a pool, I'm thinking it should set the description to the job name (possible including the number), and then poke at the api to find and terminate other pools with the same job name in their description. Sound nuts?

**Comment by mfalesni** [comment]
@seandst I can definitely add an API call to set the description so the py.test can set it. And the api call to find pool by description should not be difficult to make.

**Comment by seandst** [comment]
Cool

**Comment by dajoRH** [comment]
Lint report for commit 7ffb40ceab0ea9df0c4d2e53f18d37379aa633d8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@seandst Latest commit should have everything required for the description operation (set, get, find by).

**Pull request merged**
