### PR TITLE
change the report format to handle master/slave config.

### PR DESCRIPTION
**Pull request by amavinag**
* changes done to this file, to be inline with groovy
    scripts on cfme-qe-yamls. the groovy runs on master
    node unlike other scripts and this change helps the
    current groovy scripts to skip the slave node lookup.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d2806bd627b3fabdda9eee6ff29d5b91aa74ae5a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 687eae34a314c218ac7d832da6b69328aa5021e8:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cb392aad7d4f9cb59e837459bcca60575a3490ad:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit df17e8c01de049746ed0caa911f7b1f2ca52670b:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
I don't like the hardcoded paths but @amavinag said he will correct it in next PR.

**Pull request merged**
