### PR TITLE
fix input locator for settings

### PR DESCRIPTION
**Pull request by akarol**
{{pytest: -v -k 'test_timeprofile_crud or test_host_noquads'}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b136fe453474fbff7057515eedffdd9c64918c61:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by akarol** [comment]
{{pytest: -v -k 'test_timeprofile_crud or test_host_noquads'}}

**Comment by mfalesni** [comment]
@akarol I have put the PR tester configuration in the PR description and initiated a retest, since PR tester does not pick up configuration from the comments.

**Comment by akarol** [comment]
@mfalesni  Thanks!

**Pull request merged**
