### PR TITLE
py.test waits for sprout to become online (useful when it gets updated or so)

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 21a91909850bb779e591f4f54ec1acb30e44b883:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/infrastructure/test_datastore_analysis.py:8:1: F401 'setup_provider' imported but unused
./cfme/tests/infrastructure/test_datastore_analysis.py:32:101: E501 line too long (109 > 100 characters)
./cfme/tests/infrastructure/test_datastore_analysis.py:62:1: F811 redefinition of unused 'setup_provider' from line 8
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 80102bddf0dbbdbbf3e961b799a6d2653dcce6ae:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/infrastructure/test_datastore_analysis.py:8:1: F401 'setup_provider' imported but unused
./cfme/tests/infrastructure/test_datastore_analysis.py:32:101: E501 line too long (109 > 100 characters)
./cfme/tests/infrastructure/test_datastore_analysis.py:62:1: F811 redefinition of unused 'setup_provider' from line 8
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7f204474b59e811226d7399f4b988542f7b980e7:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/infrastructure/test_datastore_analysis.py:8:1: F401 'setup_provider' imported but unused
./cfme/tests/infrastructure/test_datastore_analysis.py:32:101: E501 line too long (109 > 100 characters)
./cfme/tests/infrastructure/test_datastore_analysis.py:62:1: F811 redefinition of unused 'setup_provider' from line 8
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Comment by mfalesni** [comment]
#1552 should solve this universally.

**Pull request closed without merging**
