### PR TITLE
Move Middleware out of Compute

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 077159c84cfd980459081119d15cb7bb517b9737:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c4d46420b59c6bf7e75c197de0b755381cada5a7:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
Changes working fine locally.

**Comment by hhovsepy** [comment]
Looking forward to get merged, https://github.com/RedHatQE/cfme_tests/pull/3055 testing is blocked by this fix.

**Pull request merged**
