### PR TITLE
Remove Service BZ and request desc change

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 497ae8555e9f2625692d70699c6d03b7a523d744:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
The changes look good, but the PR tester results indicate some possible locator issues. Please look into those test results.

**Comment by dajoRH** [comment]
Lint report for commit 74009b573d51451c030934413165a957aa827b26:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
PRT still shows some errors, but I think they may be actual bugs that were revealed by the changes in this PR. Specifically, we've got some wait_for_requests failing because it looks like some requests are never being created.

@sshveta, please look into those test failures and see if we need to fix our automation or open some bugs. Thanks!

**Pull request merged**
