### PR TITLE
Externalized wait_for

### PR DESCRIPTION
**Pull request by psav**
{{pytest: utils/tests/test_wait.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c512c9e4392858873709668fe5e3dfbc6192be4a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
The only thing this doesn't fix right now is support for our logger in the decorator, will need to think about that one!

**Comment by mfalesni** [comment]
@psav I am worried that with the current pytest architecture the only place is some global (yuck). I can't think of anything better right now.

**Comment by psav** [comment]
Yeh it's as you had it ```pytest.wait_for``` this is as best as we will get I think right now

**Pull request merged**
