### PR TITLE
Take a screenshot when exiting an appliance CM with an error.

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/distributed/test_appliance_replication.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit caadd01308380edf53e465785b7d137b2a53c0c0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b0977fdd212f3cb6d6e401e52ac17836e4458b4e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Functionality verified to be correct. @psav wants to do some more magic instead of the globals though.

**Comment by dajoRH** [comment]
Lint report for commit af8ad76744c87fdc273fcf3f3a088de27b36e334:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a64d58218c8daa8e24fbe29b4284fc555c3dd7b5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3dcfd8116217c05fe25c7a9368876892104a5bee:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 67b92d5a1d9e52b4132f5df2d18e217299b93e04:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f6d14a55aeebcea94b4dbe55d3dc2196143a433c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2492f95e934595b4f6f399e18d06af3fe46a3920:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
