### PR TITLE
[WIP][NO TEST] Sprout - Make template deletion automation possible with scripts

### PR DESCRIPTION
**Pull request by mfalesni**
This should enable us code up some logic that will be deleting the templates.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 76c780a7ddfdfd375ff51f5df3633c0eabe3e2ad:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Had a chat in IRC about this, the gist of it is
* This reduces our accountability over code changes to sprout
* Could be dangerous as we can essentially run anything, would be safer to allow us RO access to certain attributes for us to test our logic.

Possible discussed solution, is to just have multiple functions in the code base for deletion logic, and for a yaml maybe to hold which stream uses which deleter.

**Comment by dajoRH** [comment]
Lint report for commit 92872689fe6c8cedeb6b16d07511c8a41fbb755a:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./sprout/appliances/models.py:10:1: F401 'lazy' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Now I changed it a little bit, still uses the same execution policy but now the scripts are looked up in a predefined directory. There is Pyro4 in the requirements, which is similar to ruby's DRb, that can allow us to launch a separate process with a separate object that will allow predefined actions to be done. But that will need to be done yet - I think I have some code using pyro at home.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2d2e99f64b4394524f911c603bde7d65d1657622:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 91cf3d0a560125e3ca291aad2967ad451700d2eb:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
@mfalesni stated this is no longer required, functionality is added via another PR

**Pull request closed without merging**
