### PR TITLE
Fix error for not existing container_providers

### PR DESCRIPTION
**Pull request by avi3tal**
The right key name should be containers_providers

[ticket: n/a]

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4b6b40dff591f39eef7cb0da4375a5ab10b33413:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
To get PRT to test, we'll need you to GPG sign your commit and for your key to be added to our DB

**Comment by mfalesni** [comment]
@psav I have Avi's signature (of his key `74EBFDFC`, you can check), so I can add him to the YAML.

**Comment by psav** [comment]
@mfalesni sure if you are happy

**Comment by avi3tal** [comment]
Thanks Guys!

**Pull request merged**
