### PR TITLE
SSA: check services

### PR DESCRIPTION
**Pull request by vrutkovs**
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'vsphere55' -v --long-running -k "test_ssa_vm"}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e01c768bd5dab3d13e2e97393c62929b7ac08dbd:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Happy here, just waiting on a better PRT result

**Comment by dajoRH** [comment]
Lint report for commit 1bdf6e439f71be400d1325b4b1ce266335f7766e:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fc2afd1013593e522e3cb6b18f8326d77622063a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 742b1635a7ac68cccba667429327805e3b41b241:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dc9e6cbcd4d5da96f9feaa98423d4cc7e39a4fd7:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b8e6db14f754ea58a2b68cc82e5545ef39aeaa7c:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
