### PR TITLE
Added new method for getting + setting yaml config on 5.6

### PR DESCRIPTION
**Pull request by psav**
{{pytest: cfme/tests/configure/test_ntp_server.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2ff4584c4260373de8a0cd7dc604b8dea65c9260:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6506fba18df2a12583eb51c1ce1cf2c54bd85ef5:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
im wondering if it would make sense to support cli arguments to the script and only upload the new config data, then call the script with arguments

**Comment by psav** [comment]
Possibly, I just copied the original template file and modified it to suit, at the moment this is gating testing, so I'm happy to get this in as is for now.

**Comment by mfalesni** [comment]
I checked the results of the tests and they didnt seem to have errors related to this PR so merging.

**Pull request merged**
