### PR TITLE
Fixed toolbar

### PR DESCRIPTION
**Pull request by psav**
{{pytest: -m crud}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fe949fce75e7a54a59f71a61a29d594ee482a446:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/toolbar.py:13:1: F401 'ToolbarOptionUnavailable' imported but unused
./cfme/web_ui/toolbar.py:104:101: E501 line too long (103 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Beware of https://github.com/ManageIQ/manageiq/pull/4853 , that should change things.

cc @martinpovolny .

**Comment by dajoRH** [comment]
Lint report for commit 077ab55ccb6dd5838dec0adbc6fe381dec884452:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 79ff999f28353c346a37b28bd4a7e6ebbbe0c618:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ccc2621b058681bcdc154c87012ce226c61245a0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3d62818c846df939d8043f22dbea379d8db73240:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f02422b7578cd348438943124f59b747be638ed6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
