### PR TITLE
Input conversion for provider

### PR DESCRIPTION
**Pull request by nachandr**
This PR if for wrapping existing input locators in infrastructure/provider.py by the new Input class.

{{pytest: -v -k 'Provider' --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 07e55585d8d5cb6076ec340935a20be1f46ead5c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Looks good to me, but I'd love a second opinion from @mfalesni since he's been working on this as well.

**Comment by seandst** [comment]
I'd also love to see what the pr tester has to say, so please sign your commit.

**Comment by dajoRH** [comment]
Lint report for commit 58619a3e7f84ce4ebde1a25f1a7897f894232533:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by nachandr** [comment]
Signed the commit.

**Comment by seandst** [comment]
PRT was green, so I used that as my second opinion. :)

**Pull request merged**
