### PR TITLE
[WIP] extra logging for vm analysis failures

### PR DESCRIPTION
**Pull request by dajohnso**
{{pytest: -v -k 'vm_analysis' --long-running}}

### CODE REVIEW

**Comment by dajohnso** [comment]
{{pytest: -v -k 'vm_analysis' --long-running}}

**Comment by dajoRH** [comment]
Lint report for commit 0936862b9181096547429a64a7e8c440d2cd891d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34fdfcc6a3fd2d77233877ad57815f91057bc385:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 03de825c8b072b6984cfdcc887be753653a9bcb1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request closed without merging**
