### PR TITLE
Service templates rest tests

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/services/test_rest_services.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8d6147b6c5eaa08a95f769ce2e7fc144efd2c227:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e62d6795826c7410f50be19189e56bca4a78ad42:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
Looks good, merging. :+1:

**Pull request merged**
