### PR TITLE
Fix ButtonGroup to work with newer design

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/configure/test_visual_cloud.py -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 99fa598b0e7c6294e6539271a8ad429f97e2f096:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
So ,this looks scary in PR tester, but there is another PR to fix that selects.

**Comment by dajoRH** [comment]
Lint report for commit c356c0ec842f6ff7adeb6ef50cf9c2e4334a483b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cc34f90cd686f03cec057660745724059b8432fa:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e890b44147da56ab37488424695e17914fdbb2f3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9f7b2f903a74d872584a01ccc2103984ffb2cbc4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
This should be OK to merge. There are some errors, but those are for another PR.

**Comment by dajoRH** [comment]
Lint report for commit 9380598f16881bf6c9d519ff084d4bb905dae9b0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
