### PR TITLE
fix issue with save button for log_depot test

### PR DESCRIPTION
**Pull request by kzvyahin**
add button for 5.6 into log collection page
{{pytest: cfme/tests/configure/ -k log_depot -v}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c4891fe475eaf9f33de65f13867207ad8694fb3b:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 36dbb3658f1b9d8807c027c0e89912543ff617ba:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 27c9a906caefc8df11ad6d225bc4c3858ee01c32:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit aef6b5fcc11d179ab7a10eac18894d4059d97e23:

`cfme/tests/configure/test_log_depot_operation.py`:
- :red_circle: Line 14:1: **F401** *'BZ' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6bb5f12872b8682ee9f22f818acb2631cdb663c1:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
5.6 is blocked (skipping) and upstream is blocked as well but is not skipping because the BZ is in POST. Merging.

**Pull request merged**
