### PR TITLE
[WIP] : Seeding dialog automation

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b0e3bec46f0788808b29a31e07183df61429e277:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1fdfc722c24f05112c7c6d75335b9f4cc124c63a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by sshveta** [comment]
Need help here. The automation test creates a dialog and exports the dialog into a file and saves . It then needs to be copied to the appliance and we delete the dialog from the appliance and reboot the appliance. After rebooting we  check if the dialog is shown again in appliance. 

I have currently hardcoded the path where file gets saved on my system . Need help with what path it will be saved in jenkins or any other system . Sometimes the file shows being downlaoded (pop-up on the browser shows )but doesn't actually get downlaoded. 

Someone please look.

Thanks
Shveta

**Comment by mfalesni** [comment]
We currently cannot access downloaded files on jenkins due to known limitation (browsers run in wharf containers)

**Comment by sshveta** [comment]
Issue not resolved yet .Closing for now ..

**Pull request closed without merging**
