### PR TITLE
[BZ] Automate BZ 1209538

### PR DESCRIPTION
**Pull request by mfalesni**
Disabled meta plugins for purpose. If the tests fail with timeouts, then it is all right.

{{pytest: cfme/tests/control/test_bugs.py -v -k folder_field_scope --long-running --disablemetaplugins blockers}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8d6331a5d5668561ccd8962c08b58e30c5685018:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Tests didn't fail on 53 and 54

**Comment by mfalesni** [comment]
Hmm. And I even wrote it step by step according to the reproducer in bugzilla. I will look at it later.

**Comment by mfalesni** [comment]
@psav It is the reversed logic in fail_condition. Mea culpa. Will fix and re-push.

**Comment by mfalesni** [comment]
@psav Fixed. Now it should timeout on both 53 and 54. I believe upstream is still broken so that will obviously fail differently.

**Comment by mfalesni** [comment]
@psav Now it correctly fails with timedouterror.

**Pull request merged**
