### PR TITLE
Tags assigning

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/configure/test_tag.py -k "test_assign_and_unassign_tag" -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e9e52acb29414111bb5c44148c9a2ca57de44caf:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/test_rest.py:1321:101: E501 line too long (102 > 100 characters)
./cfme/tests/test_rest.py:1325:101: E501 line too long (120 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 95300cb57df0f5bb63cb895572afaa9a9763618e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by lehinevych** [comment]
Should be re-write according to new rest api structure, in process now.

**Comment by dajoRH** [comment]
Lint report for commit 91e4682dff36cde288f4daeae17222803f7d815a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 25a7e1bee3573c15734ca69b2980eeecf7a9effa:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Failure analysis pls

**Comment by dajoRH** [comment]
Lint report for commit 37fb171f8fba79426f771c53a104e64094d25037:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Previously the failure was connected with PR #2649.
Waiting for results.

**Comment by dajoRH** [comment]
Lint report for commit 50a701eccd390dc199007780a19ce522c5b427aa:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 349247c8d3f7499872f66b6d39c644905638ab99:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 45754ad6ce407da73ae2622219814e477fd453c7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3a0b27393043d4010b0488b21db9cb78bc9b18c6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
@psav  Please review.

**Comment by jkrocil** [comment]
Looks good, merging.

**Pull request merged**
