### PR TITLE
Detect missing jQuery and 50x-ish errors.

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 967efbe2254311b7cb13a3ca6e91acc42032469d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ce01049cb74cf79791acaaaf8417e778d347d6ef:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
For some reason, I saw some traceback dumps in the log file, if anyone can confirm?

**Comment by seandst** [comment]
No weird tracebacks here, so... :cake: :facepunch:

**Pull request merged**
