### PR TITLE
check vm config modified time.

### PR DESCRIPTION
**Pull request by amavinag**
* added method to check .vmx file modified
    time. as the vmware python api does not
    provider vm creation time attrib.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c88c9c1c751662daba99a2924708486190ac4b5e:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
What happens if we copy files from one datastore to another, or migrate the vm to a different datastore?

**Comment by amavinag** [comment]
it gets two attributes, 
1. current host the vm is registered to,
2. the datastore url: the current datastore the vm files are registered.
so if we migrate the vm to different datastore/host then that attributes are fetched accordingly.

the modified time of the .vmx file changes in both the above cases though(and vm will be deleted after another 'delta' hours).

**Comment by psav** [comment]
Right that was my only concern, however, it actually works in our favour as it essentially "resets" the timer, I'm fine if machines take a little longer to get deleted, rather than get deleted too soon.

**Comment by psav** [comment]
@mfalesni I wonder if we can merge this in with your metadata set/retrieve, so that when we create a vm via our automation we "give" it a created time. Though I'm happy with this as it is right now.

**Comment by dajoRH** [comment]
Lint report for commit 44d68ceecfc9145f4b2430433d78a93594a009f0:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
