### PR TITLE
Clone VM Test

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3773eb0c7854dc85154aa306701e549fe73380a0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f54685c32b18d087acbdb58e562436d241a05a41:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by sshveta** [comment]
I forgot the test have to run for both the infra providers . Changed the testgen method.

**Comment by dajoRH** [comment]
Lint report for commit 75fddba087145999f85f4b0064e34cf454490c12:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 447894bc4a4cb10b247ee96dcbdd732a64d344c7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2bc358301095bdc056f739dcf343834121e6a580:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2c7683928586278c01f23c6b44552a8c62238beb:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 281970b8ce05876dc45ccabd0d21de8bd8f9791d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f6929ba02114a34e948f28e546f8697ff59c08bb:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2e003f1db8a9d02b6e709f3e4bd895b9b3809d6f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e4f8a5747f86a50d26ae8a7362f50a96148d3206:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bd5f966855d69f4eef32276b1011be3c2c523795:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c5cad50fc703363184bb0675fc87f15b53c8733b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request closed without merging**
