### PR TITLE
ColorGroup

### PR DESCRIPTION
**Pull request by psav**
ColorGroup

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 930c4c5f6661a726f89ce8328e90f39a7698d88b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6bc928feb61187a39cba83e075c2f2df873c53fc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I see a doc discrepancy, the ColourPicker from the docstring is nowhere in the file.

**Comment by psav** [comment]
typo

**Pull request merged**
