### PR TITLE
SSA: check 'Lifecycle-Last Analyzed' is updated and disable test_vm_analysis.py

### PR DESCRIPTION
**Pull request by vrutkovs**
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'rhevm34' -v --long-running -k "test_ssa_vm"}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9ff5c28292423910085992d957c3d9c3e70e7c76:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Please remove the old tests, not skip them.

**Comment by vrutkovs** [comment]
Sure

**Comment by dajoRH** [comment]
Lint report for commit 5ee333a0ac39c37a45cd626a05f2765381d8c706:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by vrutkovs** [comment]
Should be safe to merge, however rhevm34 throws '500 Internal Server Error' now

**Pull request merged**
