### PR TITLE
Added require_fields to testgen parametrized tests

### PR DESCRIPTION
**Pull request by mfalesni**
Added require_fields to testgen parametrized tests to make it sure that the tests don't go crazy when some not-so-well specified provider will come in.

### CODE REVIEW

**Comment by mfalesni** [comment]
Lint report for commit 0a626e36d9618964a27cb24387555854a34ea77a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 36570b4194e0b46323e4aa327b0073cecf219e04:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Seems like the default for require_fields ought to be `True`.

**Comment by mfalesni** [comment]
`/me` thinks so. What about Mr. @psav ?

**Comment by psav** [comment]
I would think so yes

**Comment by seandst** [comment]
Added [WIP]ness

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2c59a5768a27594efd0ac721e2b2e62714315dae:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Removed WIPness, now the PR is much shorter, `require_fields` by default.

**Pull request merged**
