### PR TITLE
Update and extend cloud pwr ctl tests

### PR DESCRIPTION
**Pull request by jkrocil**
{{pytest: -v -k 'instance_power_control' --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit cb70387cae9f8f26b17c81d0e15ea6211765ff1d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
So, what do the PR tester results mean?

**Comment by dajoRH** [comment]
Lint report for commit 6d254c1ff58c732d88ae677386e745d570270233:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a183141528e641bc5ffe57cc941f8d846ae05d25:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
Looking at the tests, it seems OK except for EC2 instance termination failing for some reason. It doesn't fail locally and it doesn't fail on jenkins either (there is no change in the EC2 code).
To hopefully fix it in PRT as well, I raised the termination timeout from 300 to 600sec... if that doesn't take care of it, I don't know what's wrong.
I'd prefer if this could be merged (as it introcudes new tests and fixes the suspend ones) and I will investigate further if the termination fails on jenkins as well.

**Comment by dajoRH** [comment]
Lint report for commit 079a7715146966a95d8501f000bbc8f74b15ba4b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
> I'd prefer if this could be merged (as it introduces new tests and fixes the suspend ones) and I will investigate further if the termination fails on jenkins as well.

Sounds good to me

**Pull request merged**
