### PR TITLE
Added messages to some wait_fors

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ccd9700a0e7807bdb37be6fbab15692cbb78b764:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
You know what? `wait_for` might actually write a message when it starts so when you are watching logs, you know it entered the wait loop ...

**Comment by dajoRH** [comment]
Lint report for commit 64159fc2837f113711544c68515433bfdd5be132:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
> You know what? wait_for might actually write a message when it starts so when you are watching logs, you know it entered the wait loop ...

I'm for it, as long as it's at the debug level.

**Pull request merged**
