### PR TITLE
[WIP] - API change proposal

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 92c0ea294e6162dfe8e270074b1f2fe79db1a7d4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I think I got a better idea. What about inspiration from a simple property?

```python
@something
def num_host(self):
    pass

@something.variant("ui")
def num_host_ui(self):
    pass

@something.variant("db")
def num_host_db(self):
    pass

x.num_host()  # original one
x.num_host(db=True)  # db one
x.num_host(ui=True)  # ui one
x.num_host(db=True, ui=True)  # An error, unless .variant("db", "ui") is implemented
```

I just don't have an idea how to name it, so I wrote something.

**Comment by psav** [comment]
Yeh, I had something similar, but I liked having "method" be a kind of constant, like method="something" just seemed to make more sense to me. I could even make it throw errors, look up all attributes that start with the beginning part of the string and say, valid methods are ............

**Comment by psav** [comment]
Closing as a better PR is in place

**Pull request closed without merging**
