### PR TITLE
Test for hosts through REST API

### PR DESCRIPTION
**Pull request by lehinevych**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8863b7fdaae483f48bf38ae529ea7664069815f3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I see some power operations. Isn't it too dangerous to shut down hosts that are heavily used by the QE environment?

**Comment by dajoRH** [comment]
Lint report for commit c9a5f4a0d84b7cae22ce2f571d1d962e94be9fa5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Yes, but still we have the opportunity to shutdown the host according to the rest api specification. Shouldn't we test it?

**Comment by mfalesni** [comment]
I believe only in the case that we know the host does not contain things that the environment relies on. Currently the providers that we add to the appliance to manage also host our QE stuff for which this is not a good idea. We'll talk about this later but I would not recommend to do any power operations on hosts in current tests right now.

**Comment by dajoRH** [comment]
Lint report for commit 02d578f91857efb39fd02c85027d511ef4c0dede:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
I got your point and agree with you. 
However, the tests use new created hosts by fixture added_hosts and they are "empty" , so shouldn't have influence on the others or I'm missing something?

**Comment by mfalesni** [comment]
@lehinevych You're right. In that case, you can do whatever you like to the hosts, but  then I am not sure what will the CFME's reaction be to the dummy hosts.

**Comment by psav** [comment]
This will need squashing also...

**Comment by dajoRH** [comment]
Lint report for commit aa217a42c4af50355bb3f7eae92647e6f4d6cee4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I think this will also need some version constraining because eg. version 5.3 definitely does not have these power operations. Otherwise we got a lot of red coming :smile:

**Comment by lehinevych** [comment]
These methods are not implemented yet for rest api, so they will fail anyway :)

**Comment by jkrocil** [comment]
@lehinevych Im not sure how to interpret the last comment - if there are tests that would fail when ran on jenkins then we cannot merge the PR. We do not want to add failing tests to jenkins.
If the tests are really failing due to methods not being implemented, they have to marked and skipped.
On jenkins, we only want tests that either **pass** or temporarily **skip** but will be run in the future once the right conditions are met.

**Pull request closed without merging**
