### PR TITLE
[WIP] Add depot_name into log depot

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fd89f18f6aa00dc21be80c99c3b48b791f4f5b11:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a1316ffcfd3600b9c21967dd6ff1416d7174e827:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1d0fb308853892be078e46fb18b5c6fe823b6a23:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 610e23cd3aed2dafaa058b9c747d006667f92fe0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ad6962a55830f86b6dddceda7863a03f234ddc5f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
WIP to not test the blocker addition.

**Pull request merged**
