### PR TITLE
[WIP] Post results for failed builds

### PR DESCRIPTION
**Pull request by seandst**
Merging this will break trackerbot's graph rendering, since it doesn't yet understand the idea of "-1" for the number of tests (and in fact, the API currently turns those values to 0, so the flot JS div0 errors). But if I get buy-in (mainly from @psav) on the "-1 means the build failed" idea, I can get trackerbot patched up pretty quickly to deal with failed builds and then we can merge this.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit dfbc28101fe83c617fd495a660e2c67e35e11648:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Yeh, I don't see an issue with the -1 for failed build, though a part of me wonders if we should have a "build_result_code" field in the db instead. At which point we could ignore builds for which that is set to non-zero?

**Comment by seandst** [comment]
I kinda like that better. We could stick with the -1s, and also post success/unstable/failed, or some numeric equivalent.

WIPing it.

**Comment by psav** [comment]
Nice! Thanks @seandst. Are you going to add in the build identifier thing in too?

**Comment by seandst** [comment]
Yep. Migration time! :D

**Comment by dajoRH** [comment]
Lint report for commit 5b3360d91d09fa5d103e7e49a33e35c262d6d848:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
