### PR TITLE
Update CFME REST client to be able to use the 2.0.0-pre API an onwards

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -v -k REST --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8ca1b93e8aa596104e53e9d178770d17fba93217:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Do not merge, adding one more thing right now.

**Comment by dajoRH** [comment]
Lint report for commit 2853e3acb6337d74a1b03358df9a3a1809abe091:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5497a9230e74f6df3714c8f9c88756a072d3a4b7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d100055c263eb83dbc5ef7b8332b2ac9c9aa3206:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
