### PR TITLE
fixing postgresql service calls

### PR DESCRIPTION
**Pull request by blrm**
This fixes a minor issue with restarting the postgres process that was causing some replication tests to fail.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 872fe888dddb7f0718c14d19ea6415de02c2e868:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@blrm I wonder - is is gonna work for upstreams too? They already use systemctl so there might be some difference? (or not, just asking)

**Comment by dajoRH** [comment]
Lint report for commit e6fcd51f430dffaaed07dbfa29aff55d61773af0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by blrm** [comment]
@mfalesni Replication testing only runs on downstream currently, but this call should be fine for upstream as well. appliance.loosen_pgssl uses the same syntax for upstream.

**Pull request merged**
