### PR TITLE
Harden stats_matching

### PR DESCRIPTION
**Pull request by psav**
Harden stats_matching

{{pytest: -k test_provider_crud}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6fa9091ce4a0641ee640a84e1eba66960bb65a7a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 47b6b88276e35384ed74b6a269d7ec4b1bb80fa6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
If you want to stay away from the UI during db stats matching, you could do
```
ssh.run_rails_command("'require \"ext_management_system\"; ExtManagementSystem.refresh_ems {}'".format(provider_id_in_db))
```
to refresh the relationships...

**Comment by psav** [comment]
@jkrocil That's actually pretty awesome! I may do that tomorrow

**Pull request merged**
