### PR TITLE
Try handling the sqlfilter/filter difference corrently

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -v -k DeleteViaREST --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8551b47ca46af9f24e6ffcba422a919d75968c4b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
PRT run didn't actually test anything, is the logic on the pytest line sound?

**Comment by mfalesni** [comment]
Should uncollect on 5.3 ... I changed the keyword and did a retest to be 100% sure.

**Comment by mfalesni** [comment]
Merging on my own, tests passed.

**Pull request merged**
