### PR TITLE
replace random aplhanumerica name for templates with template name.

### PR DESCRIPTION
**Pull request by amavinag**
* sometimes duplicate auto-tmp-{random alphanumeric} names created,
    which caused the different temporary template picked while
    creating the temporary vm, its a bug with existing format.
    this patch is a fix for that issue.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f66a94a9320c53f99dbb44d6b09803c654d02724:

`scripts/template_upload_rhevm.py`:
- :red_circle: Line 13:1: **F401** *'fauxfactory' imported but unused*
- :bangbang: Line 344:1: **E303** *too many blank lines (3)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ccbcf388aa12f23edf5cceb1d97271ca1493850c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3257b5d985e665cdc85ad30efd68f918c0369fef:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Help me to understand this. Where does the conflict occur? On the same provider? I think it is probably bad that the random name is at module level, but surely we would only get issues if the same imported instance was running multiple vms on the same provider...??

**Comment by amavinag** [comment]
@psav : yes the conflict occurred on the same provider, on export domain.

1. the temporary file created by previous template was not deleted (e.g. auto-tmp-xyz for downstream-55)
2. the upstream upload generated the same name e.g. auto-tmp-xyz and used the downstream-55 template(which was not deleted). so, the final template name was upstream but content was downstream-55.

**Comment by dajoRH** [comment]
Lint report for commit 855eebc67d096badb24f390841ed8add3e0f7164:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34f4e20427cb9cf61a4711e14f7526a13a44d523:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5fb8893b9710d33ea7dfe75223a0281ac3fb8523:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 784d3071f1f7fd9f50d940132e1219b2bb35ddc8:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
