### PR TITLE
[WIP][NO TEST] Change the rest-client gem detection

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 7df06b0984a910f745d133ecff56d51fc017c721:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@seandst You might know how to circumvent this workaround? I could not see any devel package in ruby200 SCL.

**Comment by seandst** [comment]
I ran into something similar recently, and ended up pulling the rpm directly from internal composes. It was pretty inconvenient, and probably we shouldn't be building gems on the appliance anyway.

How would you feel about precompiling the gem (in jenkins, say), and then installing it that way?

**Comment by mfalesni** [comment]
@seandst No objections against that.

**Comment by seandst** [comment]
Card created. you need `rest-client` and I know of a couple that I need for ui coverage. Any others?

**Comment by mfalesni** [comment]
@seandst That is all for me, just `rest-client`

**Comment by dajoRH** [comment]
Lint report for commit eb1785a4da2d70705d1efd8f161ba8b6fc385aaf:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@seandst changed for detection inside MiQ bundler env.

**Comment by seandst** [comment]
This was WIP, but it seemed good to have it merged.

**Pull request merged**
