### PR TITLE
Clean up the appliance stack a bit

### PR DESCRIPTION
**Pull request by mfalesni**
Dave told me there is some weirdness happening. I did some cleanup and will see what can I do with it.

{{pytest: cfme/tests/infrastructure/test_vm_analysis.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 15b5cf48f30861e741a03d54ec3021453d79bd52:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 19094d14f2dc45e086c60f161412c37f593061bb:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fcac783780ad516853450b4993fc8e5e3f66ef95:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d79d96e8419c0d72f61ba7531b4f0cf05c20a2e9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eca6e491d21c6f8a5f8e8b11e1014e4ac3a59b72:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav ? ^

**Pull request merged**
