### PR TITLE
Entry point made mandatory

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 36263fa3556fe8183b5e5b87c179f56f95f7beea:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/services/catalogs/catalog_item.py:10:1: F401 'current_version' imported but unused
./cfme/services/catalogs/catalog_item.py:214:37: E127 continuation line over-indented for visual indent
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cad75ff1133062c472d9fd1dcf3ebb9c8131a479:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by sshveta** [comment]
some other files are merged. CLosing this one and  raising a new PR

**Pull request closed without merging**
