### PR TITLE
[WIPTEST] - Fixed some deferred element resolutions

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 54828893b1e11d9eb55e127c79a5eca07d73671b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I wonder whether we can make something like "deferred property" and write it like this:

```python
SOME_LOCATOR = deferred_pick({"5.2": ...})
```

which would be equivalent to:
```python
@property
def SOME_LOCATOR(self):
    return version.pick({"5.2": ...})
```

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav This needs rebase using the deferred_verpick that you merged. :)

**Comment by psav** [comment]
I need to go through and redo this one with the new deferral object

**Comment by psav** [comment]
This was closed via another PR

**Pull request closed without merging**
