### PR TITLE
Services rest api tests

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/services/test_rest_services.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4b45b545e568ba76153a95fc832a3778040cfad4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 075834a9bf55d72ce7808d442dff1d5965f6a30e:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_myservice.py:168:1: E303 too many blank lines (3)
./cfme/tests/services/test_myservice.py:187:1: E302 expected 2 blank lines, found 1
./cfme/tests/services/test_myservice.py:215:1: E302 expected 2 blank lines, found 1
./cfme/tests/services/test_myservice.py:221:1: E302 expected 2 blank lines, found 1
./cfme/tests/services/test_myservice.py:227:1: E302 expected 2 blank lines, found 1
./cfme/tests/services/test_myservice.py:246:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7f3b343cdcb6cf16ff3e7a72e1a41dc41a556a96:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2205f7ae35f2533fdde8bb7a862d572390d4b359:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 04aa84d473dc53c97fc089f044587ce47f16c239:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit be60a1754e9ceefac4eeff2535c7c4ed64bcb362:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Fails on upstream because of https://bugzilla.redhat.com/show_bug.cgi?id=1298624

**Pull request merged**
