### PR TITLE
Rest api terminate method for instances

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/cloud/test_instance_power_control.py -k "test_terminate_via_rest" -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 22895e691e4108434efaa1bce38b8d85756ccd10:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f12e9fb671c3291f01823ad06f8ad89c5928aef5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f6a9e59e9e767112c092c57bf68d997ffbfcae2c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4b8ea2f89189de771b36d3b2c266518354623bfe:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bea311a9a9a8855ca76c43942dfc0b1b2d321070:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5857fc14ac7f18e7cc5fb495a993675f2887eeee:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 488fb598d4c2c3f1f998d8cbe3aa7c16190790d1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Testing on upstream fails because of database table split. Fix is #2669

**Comment by dajoRH** [comment]
Lint report for commit 101387818bfd6b9d543827ffeda10913e1112ad5:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/cloud/test_instance_power_control.py:362:101: E501 line too long (120 > 100 characters)
./cfme/tests/cloud/test_instance_power_control.py:363:101: E501 line too long (114 > 100 characters)
./cfme/tests/cloud/test_instance_power_control.py:366:52: W292 no newline at end of file
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 69468c6aacb1587002efd93d82276d64824bf804:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eb10380fb0a29867fd3536892cf10ce6ee852c00:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Testing on upstream fails because of database table split. Fix is #2669.

**Comment by dajoRH** [comment]
Lint report for commit e0baec53ad7565029c245d599cbbcf7c84f2561b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 28eda293a06081ac824315750d7c1507cc2aa46f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Add https://bugzilla.redhat.com/show_bug.cgi?id=1310067
connected with aws vm, this is also connected with UI termination test

**Comment by dajoRH** [comment]
Lint report for commit 13a0c696a1a836f7a3c71c4a470c715a7eab534e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 11faf18cf528f7873a4fe148c7585eebf3f17cc9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b6de8c415bb1096708c1687729eb1a5f641262a4:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4e3d11d3e1ac561f48c1f158d537a7c69ae5525c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
@jkrocil happy to merge if you are

**Comment by lehinevych** [comment]
@psav @jkrocil  PR fails on the upstream for ec2east because the power state == off, however should be "terminated" as on 5.5.

**Comment by psav** [comment]
@lehinevych do we think they are going to move towards it being "off" in future? Should we version pick?

**Comment by lehinevych** [comment]
@psav  I didn't find out any information that this is expected behavior that's why I created issue for upstream and add blocker to test.

**Comment by dajoRH** [comment]
Lint report for commit 8d41724d998a831a6ab70d221f51f8bacb2fb623:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 238fe27854a0e6f59b92d367d27c729e94906cfc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
54 and 55 looks good but in upstream, we dont want to skip the test for all cloud providers. We want to skip only with ec2 which means we have to use https://github.com/RedHatQE/cfme_tests/blob/master/utils/blockers.py#L67 directly.
Example usage is here: 
https://github.com/RedHatQE/cfme_tests/blob/master/cfme/tests/infrastructure/test_host_analysis.py#L132

**Comment by jkrocil** [comment]
Once the issue above is resolved, GTM :+1:

**Comment by dajoRH** [comment]
Lint report for commit 480232085ebacfe812e3c698d3a61cc97cdd0788:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by lehinevych** [comment]
@jkrocil  done

**Comment by jkrocil** [comment]
Merging

**Pull request merged**
