### PR TITLE
Add BZ Blocker for 1296259

### PR DESCRIPTION
**Pull request by nachandr**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 769ee51551c76a3a0985ee8b847b52adf1278554:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/infrastructure/test_host.py:15:15: F821 undefined name 'pytest'
./cfme/tests/infrastructure/test_host.py:17:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b1fdf76420ab0ad71749026a1eef657d4503a1be:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 172a8d7e1a0cfeeb4811da555e6a5f37f5490924:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Code looks good, just checking we are supposed to be skipping ALL tests in this particular module?

**Comment by nachandr** [comment]
Yes,all the tests in this module have to be skipped until the BZ is fixed.

----- Original Message -----

**Pull request merged**
