### PR TITLE
Fix MenuWidget

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/intelligence/reports/test_crud.py -v -k menuwidget_crud --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 19208971f714ef8840ed632e81e361a4fd61e7c2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit aa35e28bb45bdb648a9337d04265442db2dd8ab5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7031fa028229f8e00e07fcc19c0f5075c573a0ac:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ce8cdbf02e6a973bb9621829c59f871de71487fa:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2d652a7d38ed397feca4b73efc4506c5f961bd44:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav  ^

**Comment by mfalesni** [comment]
Have to merge myself.

**Pull request merged**
