### PR TITLE
Added new db query methods for middleware provider.

### PR DESCRIPTION
**Pull request by hhovsepy**
Added mgmt_system stats.
Used "_num_db_generic" inherited methods to query database.

{{pytest: cfme/tests/middleware/test_middleware_provider.py -v --use-provider complete }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e9d1d904753418257a5379c314caf54ab9655fdd:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
these failures are kind a confusing, it is because of my changes?

**Comment by dajoRH** [comment]
Lint report for commit 04730ffff2a337e249938929df1ca2a79fca64ef:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
checking

**Comment by dajoRH** [comment]
Lint report for commit 16096bb2b15d60aa0c2afd577c7b1605d79d8b89:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@hhovsepy I allowed myself to alter the PR's description to correctly test hawkular-related things. Build restarted.

**Comment by hhovsepy** [comment]
@mfalesni could you please take a look? it again failed

**Comment by hhovsepy** [comment]
upstream tests passed

**Pull request merged**
