### PR TITLE
Ostriz

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2fb8797067a052d5f4d035b3bda036fbb4dbe563:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Ostříž lesní

**Comment by dajoRH** [comment]
Lint report for commit 733a9b1f1f198368d78257aabf39a940de39384d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cea5b8596f3b68a56980a1130361388b645cef12:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8da87e8b289bcb170f052c41ad692508a4188aae:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I think my [ostříží pohled](https://translate.google.cz/#cs/en/Ost%C5%99%C3%AD%C5%BE%C3%AD%20pohled) has not found any weirdness in the code. Plus I was shown a working demonstration.

**Comment by mfalesni** [comment]
Let's go!

**Pull request merged**
