### PR TITLE
[WIP] Tenant testing framework

### PR DESCRIPTION
**Pull request by mfalesni**
Very much WIP, any ideas welcome. Especially concerning automatic adding of uncollectif which seems to have some problems.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6b6ed64cf4bebdf899a907e81579f5426ccb0212:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/cloud/test_provisioning.py:50:101: E501 line too long (124 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
I think I will wait a bit for #2116 which should make some things easier for me in this PR.

**Comment by mfalesni** [comment]
And I believe it will be useful after next build so changes from BZ1189157 go in and shared networks start working. I am not sure if we could create networks on the fly. I know it is possible but not if it is reasonable.

**Comment by dajoRH** [comment]
Lint report for commit 3dcc600db4ed502396ac7fc022ddc1b9c36d27b3:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/cloud/test_provisioning.py:50:101: E501 line too long (124 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d178d1aa078e8ffa0ea6ec4109162e0e5e43c8ca:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e822c3fde217f6a0689997f872129312a92265b4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9eded7d269a93d553d62cff6ad85080b77a52cbf:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 839547ae43b8d7ca996eb48a5e10fcefbe51617f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9075748bd4abfc90260f411111916e89a9a0e6fe:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
Closing for now. I believe this was not the right approach.

**Pull request closed without merging**
