### PR TITLE
SSA: fix test_instance for windows VMs

### PR DESCRIPTION
**Pull request by vrutkovs**
{{ pytest: cfme/tests/infrastructure/test_instance_analysis.py --use-provider 'vsphere55' -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 052f1c8d099630b0d9b577570ca664b01ca39048:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Can we take a look at the PRT failures here

**Comment by vrutkovs** [comment]
Depends on #2598

**Comment by dajoRH** [comment]
Lint report for commit 5c3195697af05b3e889d4912180ea9a917b22f53:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 52d0ec5cfdc7bb285711e6241025973d95fd313e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 82ecf4f1d6af589c944b97f7d5d1f28688b203d6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by vrutkovs** [comment]
This is now required for #2598 to pass

**Pull request closed without merging**
