### PR TITLE
Vm migrate and VM clone fix

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b5f2f225bfaa32605a30ef8c2758b4f519ed6642:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c80e4dfd2ea0654bfecca7c6c398728003032e1a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by sshveta** [comment]
Request.py wait_for_request method .....if row.request_state.text == 'Finished':
        return row

VM MIgrate request shows row.request_state.text == 'Migrated' .So request never completes

**Comment by dajoRH** [comment]
Lint report for commit f68426e14dc5df1c2483a96d32cf466c97a0dcb9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 59052ce6e5fffafd3ded4bf9510626c54985767a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 33e45044bd8608a5af844f7ea27b7b9156be4583:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3154c08951173138d10b8a40dfa7e77c64f0bf49:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
