### PR TITLE
Sprout quotas + dashboard

### PR DESCRIPTION
**Pull request by mfalesni**
gosh this PR is big ...

Now you can specify how many appliances is the limit for each provider.

Added dashboard for other people to use. Incomplete, but should be operable :)

### CODE REVIEW

**Comment by mfalesni** [comment]
I'll definitely have to gut the JS out since I don't need all of it.

**Comment by dajoRH** [comment]
Lint report for commit 4c8ca891e3ac97652a6ca043bfae37269e065c15:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./sprout/appliances/static/components/bootstrap/test-infra/s3_cache.py:50:101: E501 line too long (105 > 100 characters)
./sprout/appliances/static/components/bootstrap/test-infra/s3_cache.py:86:101: E501 line too long (114 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ea95c4b630dda1b4e73357f50962946841d77470:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./sprout/appliances/static/components/bootstrap/test-infra/s3_cache.py:50:101: E501 line too long (105 > 100 characters)
./sprout/appliances/static/components/bootstrap/test-infra/s3_cache.py:86:101: E501 line too long (114 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8b3aac6f9688199fc118499a7af4bb3d1dd0c964:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e4e6e8fee070e66e74402f38b720d0ec35798f45:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f0a79e2b399aece05d63e9fee1310b0a7f73bd45:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./sprout/appliances/urls.py:3:1: F401 'password_change_done' imported but unused
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bcbe0c6df670da589a3c50843b1385f5442b82a7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 68ce1c7ec93eb9460653cd0a28f4b22ee5edd16f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b812c56c13f598f3e1a0d224db860c942772c859:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9f2ac7eed87f383ab952fe16bd2ef0c76942ade0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8b8c0f85078bf0e5b40bf6fc6aa4a6b0ad36c678:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4532a8d255387a94d97649a39c56eabfdcb4f33d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9829f12c846d748e04976d9a1c8de7802f53cb7a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 996f9e7e8aeaca6b6883ae054d63999524395897:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 159f526604c6e0818a62be0bed9633fba92aa171:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
