### PR TITLE
RSS link checking

### PR DESCRIPTION
**Pull request by mfalesni**
Notice the particularly awful solution on line 201.

{{pytest: -v -k verify_rss_links}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit dcd975a5fc3b2383bffabc6179e144ba153886b3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9d750385c342298fc64369de1f5f39a48c42b916:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2ba0d1edc3f98d1f992caa2fb913dff788828607:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eb2a57adf4e55fb32811e552e97f7079ce2c0c1c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e833c21072419b57df3054649530dc0298bfbd7a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Looks good :cake: :facepunch:

**Pull request merged**
