### PR TITLE
Taiga #19 - Improve PEM checking

### PR DESCRIPTION
**Pull request by anewmanRH**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1954d569f2429c32e544fd3746b8fe31bfb68ac3:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/test_appliance.py:5:1: F401 're' imported but unused
./cfme/tests/test_appliance.py:160:101: E501 line too long (113 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by anewmanRH** [comment]
Corrected lint errors

**Comment by dajoRH** [comment]
Lint report for commit bfca08964ebbbd2c5669b9c19a4434db392d2d2e:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/test_appliance.py:159:50: E502 the backslash is redundant between brackets
./cfme/tests/test_appliance.py:160:13: E122 continuation line missing indentation or outdented
```
:trollface:
*CFME QE Bot*

**Comment by anewmanRH** [comment]
Borked the PR

**Comment by psav** [comment]
We can fix that, it's pretty straight forward, can show you when you get in.

**Pull request closed without merging**
