### PR TITLE
Test provisioning with additional volume created from AE

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -v -k test_provision_with_additional_volume --use-provider rhos4 --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3f4f63167dde39fc1a256e0b7296a30fc68b8711:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9899a1e55f61b805ff503039a9173f7ef029c318:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
PR tester seems to like it. One RHOS4 setup failure, one skip and one pass.

**Comment by mfalesni** [comment]
@psav The volumes flags - that should be added to cfme_data.yaml, right?

**Comment by psav** [comment]
Yes under test_flags, is a big long list of all available test_flags - hopefully in time this will go away, but for now it is needed to calculate sets

**Comment by mfalesni** [comment]
@psav OK, so I will add volumes to the OS providers, push it and then uncomment flags here and repush (retest).

**Comment by dajoRH** [comment]
Lint report for commit c2a94f2eb8a4d90ad26220808d1967cb430a36f7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav should be mergeable now.

**Pull request merged**
