### PR TITLE
Added filtering possibilities for setup-a_provider()

### PR DESCRIPTION
**Pull request by mfalesni**
Might be useful as in the direct links tests since scvmm does not have some yaml fields because the provisioning is not supported yet.

### CODE REVIEW

**Comment by psav** [comment]
Once again, I would expect test_direct_links to be a "provision" based test, and therefore will be uncollected from the testgen since scvmm will have "provision" excluded.

**Comment by mfalesni** [comment]
@psav Acutally it is not a provisioning based test, it just needs a request to be created for visiting it with direct url.

**Comment by psav** [comment]
Right, but the request needs to be created, can that happen on scvmm? Essentially the provider needs to support provisioning no?

**Comment by mfalesni** [comment]
Well, you are right, scvmm does not support provisioning yet ...

**Comment by mfalesni** [comment]
Lint report for commit 841f791405eb2e9b645e397a0f19e83350aa056d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
We're cooking up way cooler things that will do this better.

**Pull request closed without merging**
