### PR TITLE
Modified to run for rhos6-ga

### PR DESCRIPTION
**Pull request by sshveta**
{{pytest: -v --long-running --use-provider=complete cfme/tests/services/test_provision_stack.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3a0c563b19f350d146c694e140f5a521b8cab080:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by sshveta** [comment]
py.test -v --long-running  --use-provider=complete cfme/tests/services/test_provision_stack.py

**Comment by seandst** [comment]
The {{pytest: ...}} needs to go in the first comment (the PR description). I've copied it up there for you and triggered a PRT retest.

**Comment by dajoRH** [comment]
Lint report for commit a4edcb2595e0c2a7ef64430981276beaac823ec8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 65cfd563b271319e878dc7c094db6e457a4854a0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
