### PR TITLE
Document the latest SSH problems findings

### PR DESCRIPTION
**Pull request by mfalesni**
Checked it, builds OK.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c66b1a5852413f14244b8177750424486d2591e7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a6591a83bf344f12f8243d277b1cea6a6da7499a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Is this actually WIP? It looks ready to merge...

**Comment by mfalesni** [comment]
@seandst Yes it is, I just don't want to waste PR tester's cycles.

**Comment by seandst** [comment]
> @seandst Yes it is, I just don't want to waste PR tester's cycles.

[WIP][NO TEST] continues to be the wrong way to solve that problem.

**Comment by psav** [comment]
I will fix that issue.....at some point.........at some time....................................0.o

**Pull request merged**
