### PR TITLE
arguments[0] can be undefined

### PR DESCRIPTION
**Pull request by matthewd**
*pretty much anything else* > "WebDriverException: Message: arguments[0] is undefined"

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fc49e7f2b7f0debe953fa0df1b35e89f515bbf27:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/fixtures/pytest_selenium.py:985:101: E501 line too long (104 > 100 characters)
```
*CFME QE Bot*

**Comment by mfalesni** [comment]
@matthewd Could you please correct the lint issue?

**Comment by seandst** [comment]
mfalesni++, I prefer the OR syntax to a ternary.

**Comment by mfalesni** [comment]
@seandst I don't think it is really possible to replace this ternary with OR syntax, just the ensurement that when it returns, it returns list inside the true clause. The ternary is IMO not possible due to checking of arguments[0] and returnning arguments[0].selectedOptions;

**Pull request closed without merging**
