### PR TITLE
Removed old domain fixture

### PR DESCRIPTION
**Pull request by psav**
{{pytest: -v -k 'not dialog and not retire' cfme/tests/automate/ }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 52254c65b932580942eb6b7a69af906ec5e83a25:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
First run was all green, I allowed myself to tweak the pytest parameters a bit to test the automate explorer more and re-run it :)

**Comment by psav** [comment]
Failures are unrelated to the domain removal I think

**Comment by mfalesni** [comment]
I suppose so.

**Pull request merged**
