### PR TITLE
Convert utils.conf to yaycl

### PR DESCRIPTION
**Pull request by seandst**
I also sorted the big requirements list because...it wasn't. :)

I've already added support for this to jenkins, and you'll see we set yaycl up to look for .yaml_key in the usualy place, so this should be seamless.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 062be87ce053c56a6475d35d7023a671a4f2e451:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Requirements have changed. @seandst , @psav ?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 86068d5bbb9c2cb64801debc0ba1dd8b4c56246e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Looks like PRT needs to use YAYCL_CRYPT_KEY_FILE to set the yaml key up.

**Pull request merged**
