### PR TITLE
Bug skip the ISO tests

### PR DESCRIPTION
**Pull request by psav**
Bug skip the ISO tests

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 7331abae5d485d2541c67c0132ac4d3498adbffc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Do these need to be entirely skipped, or are there parts we can still run?

**Comment by psav** [comment]
Entirely skipped, we can't access ISO datastores at the moment at all

**Comment by seandst** [comment]
sosad :(

**Pull request merged**
