### PR TITLE
fauxfactory, part deux

### PR DESCRIPTION
**Pull request by mfalesni**
kaboom

Looks horrible, I know.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1967367e32afee2cf74426b0ee12811a746bf78f:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/cloud/test_providers.py:4:1: F401 'fauxfactory' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b4fc67be8291befe8745f5de348909b728062890:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
This is going to have an abysmal running time :smile:

**Comment by seandst** [comment]
@mfalesni Looks like this needs a rebase. I'm also thinking that this change warrants a blog post or an email to the team, so I think you should fix the conflicts, merge the change, and send out the notification that  we should use fauxfactory where we can.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dfc72c62fd5071eabda17c21e12154e9f9c32f1c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Checked the last run and it didn't look like any of the failures would be this PR related. @seandst  ?^

**Comment by seandst** [comment]
You've fixed the rebase and emailed the team, so all that's left is for you to merge it, I think.

**Comment by mfalesni** [comment]
Ok, I am now going to let this bomb explode. Banzai!

**Pull request merged**
