### PR TITLE
Tree -> javascript

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -m crud -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ed29a8287908bcf07671efc11e58a164feec652f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1daef167cdb14a1968255f31e946502286331c3e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c92e8c2d98667429de0c970552afa30e968bd6af:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1d49b58e8dcf48eb64960e64badd79de450c5862:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9bf8d8ea3034988df5fde4add9163648e369729a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f0ceb8fbeed1b5a8b81eaade229011c65ee20aed:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:70:1: F401 'wait_for' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav I will describe how it works now:

* You can pass really anything elementable. The Tree checks that if you passed something, that can be an ID ([a-zA-Z0-9_-]), then it treats it directly as ID.
* If you pass a locator or an element, then it will lazily evaluate the element to retrieve the tree id. The ID is then cached and the element used for retrieving forgotten.
* Because of the laziness, it should work with all current uses of Tree. Eg. `Tree({verpick})`
* I tried to convert all uses of locator to uses of the ID inside the Tree class.
* I added a `locate()` that yields `#<id>` and that is passed to the tree reader function.

I am thinking that with the size of scripts increasing, there is a package called `jsmin` that could be used to minify the scripts upon `js.py` load

**Comment by dajoRH** [comment]
Lint report for commit 9fe67387bcf7a8bc1115e7f946b966c888607e98:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:70:1: F401 'wait_for' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 21dc1e2fb71298f361c1c8948c67e2926db7b47b:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:70:1: F401 'wait_for' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 02fe1f0f89c5f23390a0dfd4270718fbc90b1998:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:70:1: F401 'wait_for' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 565d0efc1e7988745567728143ad568b6ff587b7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6ce3819af1209646c33501b7a3159f2235ada264:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav There is one problem with this approach which I successfully mitigate in the expand_path but I haven't tried it on the read_contents yet. Some subtrees are loaded by ajax apparently, then the childList is null. And since it runs in one thread, it seems to not work when you wait inside the javascript. I mitigated that in expand_path by "gradual advancing", that when it faces such item, it stops, tells python to wait for ajax and then python will run it again (until it gets non-False). With read_contents, I suspect that in some trees, it will have this issue and the same approach will probably not be possible since we shave milliseconds there and doing it again and again for all subtrees could be a slowdown. I think the code for it could be rewritten somewhat asynchronously, but I did not think about that yet ...

**Comment by dajoRH** [comment]
Lint report for commit ef976d2f7031ace2806c98bf0cd7b0ee9d440859:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d079e21e2671a5d0c76409dae5be43fe8db71a1a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5afde8933959cf6c5d9778cf3e31e79a7f0e8402:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5510958175d899637b4fb0e1fa14af0f048436ab:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0b3829508d2e3c49fb55d1141fab8f0dc23cdd40:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
One last caveat remaining, the `test_role_crud` in `cfme/tests/configure/test_access_control.py` is failing for some weirdness I cannot reproduce. It cannot find an existing thing in the tree, and it does this only in this test so far.

**Comment by dajoRH** [comment]
Lint report for commit 695bf159b3a331805c67c0d22f8b037aa359180a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 11cd50520cd7bc8a668be3b6ad4b123a8e61a947:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ea1cd1064801de39f1ef2d54bd8923fd71518311:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a50f39822df9114eb7a2b96a7e68a7039a1b38e1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 44ee4ff251ea50a2b3c491230d91d0a482363ea2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Asking for a review.

**Comment by dajoRH** [comment]
Lint report for commit 154ba29e3ed8fd4245b6a3e8c7c772cc6584a6b9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
