### PR TITLE
Try to fix the advanced search problems for 5.4

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f5888090b85a467afbe2e3fc6ce785a98f9c3221:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5c405ddaba8ab3c1be3a14dd66276f9ffeba17ac:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bb17da3131e4f7865d85d52690c4abcd9b77edc4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
OK, so the errors are caused mostly by https://github.com/ManageIQ/manageiq/issues/2322, I think this can go in

**Comment by seandst** [comment]
I'm not seeing the connection between some of the `NoSuchElementException`s and that miq PR, they look like actually broken locators.

**Comment by mfalesni** [comment]
@seandst As I say, the delete locators and so are probably somehow affected by the problems that the advanced search has because I checked those locators and they should be correct.

**Comment by seandst** [comment]
Seems like the tests should be skipped by a blocker on the miq issue, then, if the resolution of that issue will make those locators work.

**Comment by mfalesni** [comment]
@seandst OK, I can try tracking down the Delete element issue but the user input errors are 100% that GH issue which I can mark.

This reminds me I should devise some logic that disables the GH plugin for the non-master builds ...

**Comment by dajoRH** [comment]
Lint report for commit 0687410ccd53256a5c0a3f1ee2ab8472f124ad1e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
