### PR TITLE
Parallelizer slave grenades

### PR DESCRIPTION
**Pull request by seandst**
Throwing grenades at slaves doesn't break a parallelized test run.

{{pytest: --collect-only}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d9bdc20fb9ef86886f81dfef9b7002eefa46f339:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit caade757b7a9b454cd53668c61c67c5fda8e903a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
`flags=zmq.NOBLOCK` support was removed, since the slaves were still effectively blocking on a master response, and the master processing got broken out into a thread a while ago, so we can block all we want now. I also saw that unmetered zmq communication resulted in the sockets getting out of order. This is probably a bug in zmq, but adding the 10ms tick rate in the recv thread keeps communication zippy while (apparently) preventing zmq snarl-ups.

**Comment by seandst** [comment]
This is such a ridiculous PR that I think I'll let jenkins test it for us.

**Comment by seandst** [comment]
Jenkins approved, even though a misbehaving vsphere made things difficult.

**Pull request merged**
