### PR TITLE
Fix accordion

### PR DESCRIPTION
**Pull request by psav**
{{pytest: cfme/tests/integration/ }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 70283600a1ff2e8feea4eb9af9999b7a26f69222:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav, I am getting this when using your branch:
```python
In [4]: accordion.is_active("Saved Reports")
Out[4]: True

In [5]: accordion.is_active("Reports")
Out[5]: True
```

That is caused by the `contains` operator here:
```python
NEW_ACC = '//div[@id="accordion"]//h4[@class="panel-title"]//a[contains(., "{}")]'
```

This did not matter with the old version because clicking multiple times did nothing. However, the new version opens/closes so this needs to be addressed somehow. Maybe just replace `contains` with `normalize-space`?

**Comment by dajoRH** [comment]
Lint report for commit 9d421477e44cbe56cd61a053dd10e90b588475cc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
This looks OK and the errors are not related to the accordion.

**Pull request merged**
