### PR TITLE
BZ blocker for BZ 1265404

### PR DESCRIPTION
**Pull request by nachandr**
https://bugzilla.redhat.com/show_bug.cgi?id=1265404

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 0efdcb0102c324c8464cb75128ce2265ac42edd4:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/test_soap.py:20:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d0c330335b80fe1ec827b38f18843b69f40067a7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@nachandr I would rather put it in one meta. And I see there is not a list in blockers, wjhich should be rectified by my suggestion.

**Comment by dajoRH** [comment]
Lint report for commit 88743eb06402973be7ae4842a62e66f485a02672:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
