### PR TITLE
Catalog tab field is missing when "Display in Catalog" is checked.

### PR DESCRIPTION
**Pull request by akrzos**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fc1ec6fa101064ccec0f8797afc6071ec1d763ee:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@akrzos Which test was this? So I can add a metadata to point the PR tester to that test.

**Comment by akrzos** [comment]
@mfalesni The issue this addresses blocks me from running my provisioning workload which is currently maintained my my own fork: https://github.com/akrzos/cfme_tests/blob/perf_benchmark/cfme/tests/perf/benchmark/test_appliance.py#L463

I believe it also prevents some of @sshveta's tests from completing.

**Comment by mfalesni** [comment]
I guess this is ok to be merged.

**Pull request merged**
