### PR TITLE
None handling

### PR DESCRIPTION
**Pull request by psav**
{{pytest: cfme/tests/cloud/test_provisioning.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 47f6b155321f3f0ca7447f6248856b011e2da0a1:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:1097:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e15aa7f0fb08605aec803f259521e326b6b1e797:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:1097:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0b65cbf5cc69c52d7838b4f5bc9aafe00d807a77:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:1097:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 44f43f704f6dfe1b882324035fdf95f381deed81:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
@mfalesni @seandst - Let me know what you think

**Comment by mfalesni** [comment]
so if `none=` is set to something, it treats None differently than just ignoring it, right? Shouldn't we have a separate class that would signify a "none value for a UI element"? I wonder if this can make any trouble in the future (something gets None by default and when filled, it won't be ignored but something will be set). Apart from that, I think it is good.

**Comment by psav** [comment]
@mfalesni yes we should that is coming in the multimethods removal, when we have common base widget for all widgets

**Comment by psav** [comment]
I agree this is a bandaid for now

**Comment by psav** [comment]
Well.....for most iwdgets, if they get ```None```, it ignores......Select is the only different one now, but if ```none``` is not set then ```None``` won't do anything and if ```none``` is set and you give it ```None``` I guess you would expect it to behave and either set it to the ```none``` or ignore it like the ```None``` does on other widgets.

**Comment by psav** [comment]
Look at all those ```[Nn]ones```

**Comment by dajoRH** [comment]
Lint report for commit 087763e8b4368914ba91bb08a091eb0b797ae0b0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Looks good. If you want me to merge it, un-wiptest it.

**Pull request merged**
