### PR TITLE
EC2 events

### PR DESCRIPTION
**Pull request by nachandr**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit a0867edbe3a4dea12a02cdf0217f557409471238:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7ef4bd638e75269c5c28809596361253a791bdbc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by seandst** [comment]
superseded by #2085

**Pull request closed without merging**
