### PR TITLE
harden form filling

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/control/test_basic.py -k alert_profile_crud -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9a040df36ab6118d6eca16f570c9ecb811dab9fe:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fd92e2a7046b493c0578d1f9dc6bc83ea9b6c624:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8e6626d680f433072519dcbe112a39850e0e24a3:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d1e5e221562231360173e8088bc32b6c698c0b1a:

`cfme/web_ui/__init__.py`:
- :red_circle: Line 2814:16: **F821** *undefined name 'sself'*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8f246fd3057867e3a961492a75542ac8328ee125:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
Not required anymore.

**Pull request closed without merging**
