### PR TITLE
remove old stale kwargify

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -v -m meta}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 49e84291b6ad36311973470c5313cff258d5c906:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./utils/__init__.py:3:1: F401 'inspect' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eb307f692d3052acbbb962274a1b8cfa0fba12f5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Assuming identical interface ;)

**Comment by mfalesni** [comment]
@psav Should be. This was the original version that I put out in the separate package.

**Pull request merged**
