### PR TITLE
SSA for templates

### PR DESCRIPTION
**Pull request by vrutkovs**
{{pytest: cfme/tests/infrastructure/test_instance_analysis.py -k 'test_ssa_template' --use-provider='vsphere6-nested' --long-running -v}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b4f69a4ccc90d1fc88d9e85484c88cae0b30cc69:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by vrutkovs** [comment]
Ignore this for now, there is no ```vm_analysis_new``` section for vsphere6-nested

**Comment by psav** [comment]
Hahaha - I was about to hit the big green button :p

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b5e77980ad2132ea027bf83e7594f4031f149823:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 58ceb78b807aca01fd10ff44ed213eeb25ed74fe:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by vrutkovs** [comment]
Oops, host data in yaml is invalid

**Comment by dajoRH** [comment]
Lint report for commit a5828d5fcd7ac1543556784b7639d6546da3cfb2:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
