### PR TITLE
[WIPTEST] Some i18n testing

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by jzigmund** [comment]
@mfalesni I believe that we haven't specified any list of those kind of translations yet.

**Comment by mfalesni** [comment]
@jzigmund I hope you'll keep me informed :smiley:

**Comment by dajoRH** [comment]
Lint report for commit 5647310429434f4b3d0fd14d86524c3d497c0913:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Requirements have changed. @seandst , @psav ?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9d3c78448ecb7d1f1cf4c20ee256c5dd82db10a9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
@mfalesni stated this one is a dead end for now

**Pull request closed without merging**
