### PR TITLE
5.5 service catalog fixes

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4af288c9c446beedf124c3fc9a6c98787d53f1e3:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 98d12f0caed7c28fbff4001ef5b9dfb2da96567f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c91ad8cce8e0259f1f9d2cd9c14ce6013a3ab1cc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@sshveta Since PR tester is currently a bit dead, you will probably have to run the tests on your machine and paste us result on IRC in order to review and merge ...

**Comment by dajoRH** [comment]
Lint report for commit 49de6f9a10ca7d5a90b8a7711a3ee7a6bfb811aa:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ab0adf02e397b4bd6496f5978140ff0b4cbe0186:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
