### PR TITLE
Vm events

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/infrastructure/test_timelines.py -k "TestVmEventRESTAPI" -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b5b032529c8341970df79a79777b1d4304017d30:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/infrastructure/test_timelines.py:149:5: E303 too many blank lines (2)
./cfme/tests/infrastructure/test_timelines.py:183:101: E501 line too long (104 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 54d174d9466622b9987efeb86baadc5a45d2ae22:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Just wanted to check that the tests that were removed like ```test_provider_edit``` have a new home?

**Comment by lehinevych** [comment]
@psav yes in PR #2635

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4fa756ab094658874222c237b0e2525a6e666457:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/test_rest.py:11:1: F401 'deploy_template' imported but unused
./cfme/tests/test_rest.py:12:1: F401 'wait_for' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 462fe8e71504cb2116c6b26c7d6f7bb3adc46419:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 934872b01338bae7ac906f9943c929b7d80dd30d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
On line 15: `pytestmark = [pytest.mark.ignore_stream("upstream")]`

This makes all the timeline tests not run in upstream.
There might be a good reason not to run the UI tests in upstream but I see no reason why to not run the REST tests there so we need to remove the module-wide pytestmark and apply it only to the UI tests.

**Comment by dajoRH** [comment]
Lint report for commit b54d47fc19a47546235682a4312a35cefb285a73:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d48a2f2a9fca57a5faf4bebc24805c8dbec5035b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
Looks good, merging.

**Pull request merged**
