### PR TITLE
Test session timeout

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1d7f2c91f3526ca2ae9cea242618b4c0321f13cd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6d3a68f58bb2e9bcf2ecbba89f91eb755e824c24:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cf00e6c7c451b9dd2abe9ef495920632c6aeaa76:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit aa0115abc216aa9d3a87568a0c577aaa7a04af2c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ac62f56131925b48c53e8f4ad2c6653869a0ed64:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4abf94eed6706b6fa4d76e47fee5ac90bbeacd70:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bc1c0c2a6b74987f91cbb33c0cc6ea68d0f33a5d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 908b877f733f7e9d8be93fe71194c958ae3b8fe2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f0b73a6bdd89fa3bf887fc595d9f404ee42593d3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
PRT looks like it's pretty close, maybe some upstream/downstream locator differences to deal with.

**Comment by mfalesni** [comment]
@seandst I had the check running properly but I kept getting weird errors after the test to return back the timeout. When I tried to circumvent the issue, then even the check stopped working :(

**Comment by dajoRH** [comment]
Lint report for commit b09eb956c1d6514fb9c0b1ca1ecd7a7af845bd0d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 29c7fe8dafbe3ddbce746330dec3bf6ada36cd96:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/configure/test_session_timeout.py:32:101: E501 line too long (101 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d64695e0b6f5d7b05c19a3e6f3d9e42cf8248b8b:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/configure/test_session_timeout.py:32:101: E501 line too long (101 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0e701123566939acde1baeec065874cc75336025:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I have squashed it, now it passes also on 5.4, upstream failed due to sprout but I expect it will be the same as 5.4 does.

**Comment by psav** [comment]
Does this mean that everytime we run a test it will set the time? Can if that's the case, can we have a database getter if we don't already :)

**Comment by mfalesni** [comment]
@psav it should be perfectly possible to set it via the database yamls. And this sets the time only twice (5 min in the beginning and back to 4hrs in teardown) so I don't see that as a problem.

**Comment by psav** [comment]
I only want a getter to check before it sets......if I am running a test locally, every time I run it, I have to wait for the nav to configuration page, which is one of the slower ones iirc, so if the "check/getter" can be done via db, that would help us out.

**Comment by dajoRH** [comment]
Lint report for commit b5c23faa3ea501d1237fe95974d67334b4ab3097:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav I added a db yaml check so it runs the set only if it is not set already.

**Pull request merged**
