### PR TITLE
Compliance testing

### PR DESCRIPTION
**Pull request by mfalesni**
One test for starter

### CODE REVIEW

**Comment by mfalesni** [comment]
Nope, seems it still has some issues ... grrr

**Comment by dajoRH** [comment]
Lint report for commit 20945bc3a6e6b96339c41e2f4e77c07d39cde15e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0d1fe0662f8f684fe252d081ee8070e69a79184f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7ab06b89b543f1e4944275f0a5c9560e3a92285c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8824dcf6334f991365518c53dbe68fd86655cf40:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Lint report for commit 9911b00da94be483e6321149b2f9cf251d833f97:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b040a6b06b4c74e138fe93849550a80cc4c88c30:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Funny picture aside, I think these commits could stand a squashing

**Comment by dajoRH** [comment]
Lint report for commit eb57e863d84bd7e8af6fa5f0b0aec114f98edf04:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0d2c537f7c58f769c60c26762939debf7d0cdf95:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 79de7d7b8ec39b856618f7f813756ac8898eaffd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ab8ba1755dd150f4ff6b7b5d53d8f4f6f97370e7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9a0071cbf24aec4f098d44e1bf0de4fe68d4493e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 326161a97672cfb1a447fd9647b0a190bcdcf2ec:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f9f566ef199595b24bb5317a36c1a04212f7ceb8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6dcec46ee86f137e5e5b4a8746e586d3f00b5ba3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 71b9308967c39d619364a6fdbc20c42958c88c0e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e00b29342ca62e65f37abb7f9985284adfaa78a1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c7985bfcec98a807a29c65ee8ec6555081af2277:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e3ad5911df74c67b4dbbc7b56a1dbbc2f8c99195:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
