### PR TITLE
Disable swap for configured appliances.

### PR DESCRIPTION
**Pull request by mfalesni**
* Disable swap for configured appliances.
* Consolidate hte templatizing code (Sprout now calls the generic method rather than doing it in the task).
"

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3440fe218de3d9bdb4955da1a3959284e48b0b9c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Happy to merge this, but wanted to wait until sprout was ready

**Comment by mfalesni** [comment]
@psav This needs to be tested in teh appliances yet as fryguy pointed out that it might cause some division by zero in the CFME code working around OOM killing and such things.

**Comment by psav** [comment]
OK, so at the very least we can turn down the swappiness value right?

**Comment by mfalesni** [comment]
@psav That is definitely also an option but won't prevent us from the swapping when it occurs.

**Comment by psav** [comment]
Right, not sure what to do on this......if turning it off will kill the appliance.......let's just change the swappiness value

**Comment by dajoRH** [comment]
Lint report for commit 7c4781b65db4ace59e26d281297376b05368a072:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
