### PR TITLE
[WIP] Sprout unconfigured appliances

### PR DESCRIPTION
**Pull request by mfalesni**
* sprout offers unconfigured appliances
* urls redone

*WIP FOR NOT TESTING IN PR TESTER*

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3136c530b26a66d58ee1a8f5bdfcc1c8c36ce75f:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./sprout/appliances/migrations/0014_group_unconfigured_template_pool_size.py:17:101: E501 line too long (137 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2f8026e59b857b50a91195a9fafbae6f093f37e1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
This will probably have to be merged banzai style and tested on real sprout since the real behaviour can't be tested properly on a local machine. I double checked the code and tested the template retrieval but it still might produce some glitches.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7a9c377e0eaa789ebac2b0e81b1856ff506614bd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a4ed2ef6547d39ac12c6ecd2c7fb4d182238c498:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 672dc9bb60e8acd2c3852022615ac596c75a4882:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e4b1fb65661d3eee6b9191c5026cca2ae10395ad:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Banzai ninja merge. Will roll back if something goes really wrong.

**Pull request merged**
