### PR TITLE
esx_direct_host no longer randomizes the host

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b0e8a84e8da5ad287deb34d37763784b532b164f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fffc1b3aafacc34fa243a6d89b4bd0b9b983e9bc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d95b76ecc7244f2289ec02da88460b8e1a093d0f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c5b8311327b6b9d8376cddc057656d8c9717ba8d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Failure analysis pls?

**Comment by dajoRH** [comment]
Lint report for commit 9a6d36f360c355e350375f53c38cf1d5ee22ad08:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ebba9c497b3182675ac21921d199b8e9c6892e3f:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
