### PR TITLE
Enable port overriding.

### PR DESCRIPTION
**Pull request by mfalesni**
*Slightly* ugly solution, I admit I don't like it but I consider it good for now. I somehow checked it in my environment, it seems to pick up the changes.

@petrblaho , can you pull this commit over my branch when you test it against an appliance deployed inside the OOO setup to see if it works properly?

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 014c4d7d729484147d0904337e3df88da56d9880:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 53aed9deb45b04c99fe6d2b2c7bb1050159ea8b0:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
I think it's more than slightly ugly with the module-level constants, but I do think that the behavior is something we should have. Why not use something in the env config that SSHClient and Db can use?

Is adding a port to base_url necessary? Since we were just returning env['base_url'], it seems like putting the UI port in base_url would do the job.

**Comment by seandst** [comment]
Also, I'm generally fine with this approach as long as we have a card tracking it to make sure we fix it up right eventually. Of course, I'd prefer that we fix it up right before merging it if we can, though. :)

**Comment by petrblaho** [comment]
@seandst we have already found some issues w/r/t UI port .

@mfalesni is working on it.

**Comment by dajoRH** [comment]
Lint report for commit b3c8bf60205363e06b931e88c5f75dfbc696b691:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@seandst I was just rewriting that to _work_ and I found out we have to rewrite that at some point. I believe that some kind of dependency injection would be handy in order to always maintain fresh data. This _"global hell"_ with handling appliances, selenium, ssh and database we have now can make orientation in the code quite difficult, as it showed up (store.base_url loads up from conf but can also load from the last IPAppliance, but IPAppliance was referring to store.base_url again). Having some container, solving dependencies and I believe eventually a factory for all our UI objects (so it can pass itself to the object in order to make the object possible to have access to all the things and being always up-to-date and consistent, but in controlled manner) would be good.

**Comment by mfalesni** [comment]
I sincerely *hope* this does not break anything.

**Pull request merged**
