### PR TITLE
Updated BZ for host analysis test

### PR DESCRIPTION
**Pull request by jkrocil**
All RHEVMs including and above 3.3 are affected

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ebf0741463241673bb98e78b6cef7761a398ca8f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Can you wait with this until #1570 gets merged and then rebase it on it?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit caf1b17c44a3c5b18431f12b2199c85593dd6cb3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
