### PR TITLE
providers: rec_total returns int value now

### PR DESCRIPTION
**Pull request by vrutkovs**
{{pytest: cfme/tests/test_utilization.py -k 'test_metrics_collection' -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d7985c1d99fc18fae600383cdc1ab52cb6a17768:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ac6a94fe902bc56fa33e69826ecc38629f99d1d3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 09420a85f4f4e5f21aa1602bbe740f5c8c8ece33:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 78d44a7c80a98e5b11a17ec152a396ad56244e9a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
`rec_total` does return only `int`s now but I also noticed that `_get_rec` can return `None` into `rec_total` in case the offset for `get_rec('first')` is `None`... In which case the `rec_total` would raise a `TypeError`. And the same with `rec_offset` actually.
So now I'm wondering - are those scenarios possible? If so, we might want to have descriptive exceptions raised from `rec_total` and `rec_offset` instead of the potential `TypeError`... unless you're sure that can't happen :bulb:

**Comment by vrutkovs** [comment]
@jkrocil right, a ```TypeError``` would be unhelpful here. The scenario is possible - ```get_rec('first')``` would return ```None``` in case paginator is totally broken. It should rather throw an exception - any suggestions? Would a generic ```Exception/AssertionError``` do?

**Comment by jkrocil** [comment]
@vrutkovs I would go through the exceptions found [here](https://github.com/RedHatQE/cfme_tests/blob/master/cfme/exceptions.py) and if there is nothing useful feel free to add a new one

**Comment by dajoRH** [comment]
Lint report for commit 44d55e93ae1cd1ad4045a1657c8c1a69a38443ce:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I think I like it, there are two places with white spaces that need to trim a bit but otherwise this is good.

**Pull request merged**
