### PR TITLE
Fixed automatic InfoBlock type detection.

### PR DESCRIPTION
**Pull request by mfalesni**
List accordion (the one in left eg. in Provider details) was mistakenly caught by the form type locator, therefore failing everything. Now I have put a check in it that ensures there is a table in it.

I could have done this simply by filtering by `is_displayed` but I don't see that as a clean way to do it since each call to `is_displayed` is a slowdown.

I also found there were separate instances of `InfoBlock` in some places, found and fixed that too.

I also discovered the form type infoblock does not have to have the fieldset as the root element. I then had to add additional selenium call for the detection :(. But it works now.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 38a48bbded626f69cff46366d6c487bd17e7ebaa:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
One more issue to solve.

**Comment by dajoRH** [comment]
Lint report for commit 30224f3686f8830c87c91c62e6c07de463a935f5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dff78e5772932e46ff46162f4b01250e25985a73:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
