### PR TITLE
Jenkins fixes

### PR DESCRIPTION
**Pull request by mfalesni**
Could not verify the empty tables due to #1730 being pissy on me, so just guessing that'll help.

{{pytest: -v -k 'metrics_collection or order_catalog_item or custom_dashboard or widget or host_drift' --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c12a26e38a65af5f1390a928871d2305939f14e2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2ac1f7845fe7e858161a0c517bc04fd88fbb5e32:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 84846fb7c3a73e1139342f17a3d7fb6dc82e9fbc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9a9da49b4c6fc5b4665dc1c1c37e4d8654335ecc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a65718f94ec6cef63992e3faa99327bc9b36be08:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e3bd2912bb21f6588e1013158da08001c4c6c164:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
https://github.com/RedHatQE/cfme_tests/pull/1735 should fix your transport issue

**Comment by dajoRH** [comment]
Lint report for commit 3dcc647149e12d809ebeb89b3be9b80b8ad4fb8f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f6fbb444d0d8b621921c2f0c48dfbb602968aa6b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
