### PR TITLE
Test default dashboard widgets reordering using drag&drop.

### PR DESCRIPTION
**Pull request by quarckster**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 21c566fea32733b8098806aa0a649303a553b697:

`cfme/tests/intelligence/test_dashboard.py`:
- :heavy_exclamation_mark: Line 116:77: **W291** *trailing whitespace*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a2f57c1e0c4d486af80678745ae58d0b0a3d4a8a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by quarckster** [comment]
@mfalesni please merge

**Comment by mfalesni** [comment]
Yeah, the tests you added look good. Merging.

**Pull request merged**
