### PR TITLE
[WIP][NOTEST] Sprout - Improvements around templates

### PR DESCRIPTION
**Pull request by mfalesni**
* Suggest template to delete
* Improve UI
* Templates now track their parents, will work only on newly added templates

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 86f07841ebc9062b5d7d1d8897e32ca793511d75:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ed05e257e83495b606b89f288f767a520afb2b53:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f942c03d412038ba96b9507707a1dc7c9a82d781:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Can we do a sort of "stupidity check" here? I can then merge and update and test out. In case something is wrong, I can roll back.

**Pull request merged**
