### PR TITLE
dockerbot - checkout master before posting results

### PR DESCRIPTION
**Pull request by jkrocil**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6a131ad742dbf2da6f4315adc3ae732c2f89e2dd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
So, the security issue should be resolved, however the pip issue (waitfor not present) will still be present if signature is bad because the pip update is run AFTER the sig check. So I recommend making a global variable tracking whether the pip was run and separate the pip update code into a function. Then the function will only update pip when the variable says it was not run. Then it will be called in the place where the code of pip update was before and also after the `git checkout master` in the trap function to post the results.

**Comment by dajoRH** [comment]
Lint report for commit e7965df3f59e6d97fc04fcd595b0f41a6cbd7396:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav What do you say on this?

**Comment by psav** [comment]
This looks good, I'll have to test it manually first, but it looks like it should do the right thing well

**Pull request merged**
