### PR TITLE
[WIPTEST] OSE provisioning code

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/integration/test_openshift.py -v --long-running -s}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1032b1e5f0088c11c70fdb2e8b05a8078025d99f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 01f85a38b45f9843e82a081ee485e803059e3197:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f8552f95dfd8d256f831818ae3235bff0b1783fa:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:145:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ab2c713032865f5416070844dda57dde09b5e260:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:159:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 363dd61e5f8deb57bea53b7be5b0de34befb1c63:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:165:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2759513e25b3b7c608a411c350f62669dd9a0e1e:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:165:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1ef559d7228f694fce6812a9c7a7da6b0593ea74:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:165:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 48d99bbaefc846a46dc8c6f5978cdf7cd79b4306:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:165:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ea79f6971e669d0a60f04a4371fcd0f787abeb0e:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/services/test_openshift.py:165:9: E265 block comment should start with '# '
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f30c7155c4e5df9730d69121e391ce118976acb4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 51cf56e1afc2d44ee3d74214e9896b68acbaf7d7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1026569247d21ebf89aae5caeb2c36a33b7346b6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 10d88dc3947acf47ffb80c6425b6b7b8af36a2fe:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ac90093007b5903ff07ffb2278ea21333a868dce:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 805675bb6d507d67ee1323c000ae6177db9ad25d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c401cefa1b7102be5025a1a51e0230d2bc368ed7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5dfa4612099b797f90be72c99823e610b2ac7f4f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0204903fc6121ae411a5b9a09b49bb27b87bffd4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Closing as will not be implemented via this team.

**Pull request closed without merging**
