### PR TITLE
Retire vm via rest

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/infrastructure/test_vm_retirement_rest.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit a133c6fb3951bced339ca03622c042e44ed5efa2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 767ce5a036325ac5fd07d9090604f96c34fdaa42:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/infrastructure/test_vm_retirement_rest.py:1:1: F401 'datetime' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by lehinevych** [comment]
Blocker on upstream is #2669.

**Comment by dajoRH** [comment]
Lint report for commit 8d0a693777fa86d3df748fb134956d6654bd8b55:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8f81899f951a71cf7f8eb8eba8d75b685eb9633b:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fc580cfdb3f591f612c150eb5cb043a6b88313d6:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e20aa1295e2c6c916f62eec65aa85d1c3e6e305f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 59f2482b4b9ebacfccab88d6ac894fc49fa49c08:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0d3b616c208405f791df0c60ec515ccc2d2f4a0f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9186ff3ad4c911d8fb39e13e8fb7eddf66044447:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
54 & 55 passing, upstream skipping (upstream issue). Merging.

**Pull request merged**
