### PR TITLE
Support SSH timeouts to prevent deadlocking

### PR DESCRIPTION
**Pull request by seandst**
We've been seeing a few instances of infinite blocking on socket reads, including via SSH. I'm working on adding timeouts to all of them where I can, so the automation will at least error out instead of never ending.

The default timeout is 20 minutes, but if we see instances of that not being long enough, all of the `run*command` methods support the new `timeout` kwarg.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e2aa72256294fc92cd5d833ba8c0e3f3c81433b7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajohnso** [comment]
@seandst I wonder if we should build in a auto retry looking something like the following to try and minimize the failures on some obscure socket issue?

run_command(self, command, timeout=RUNCMD_TIMEOUT, retry=True, retry_count=1)

**Comment by seandst** [comment]
I'd be happy to tackle that in a later PR (or really open up a card for it), since that's a bit more complicated.

As an aside, I'll also point out that this problem seems to be affecting all sockets, not just SSH, so it will be difficult to solve in any general way. :(

**Comment by psav** [comment]
OH PLEASE MERGE THIS!

**Comment by seandst** [comment]
hokay then

**Pull request merged**
