### PR TITLE
Deprecations

### PR DESCRIPTION
**Pull request by seandst**

### CODE REVIEW

**Comment by seandst** [comment]
This was originally based on #1809, but I've rebased it since then, so the first two commits aren't the same ones in #1809. I'll rebase once that's merged.

**Comment by dajoRH** [comment]
Lint report for commit cafc7c90b9b08374549b175ee9097ccd6395168a:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./fixtures/templateloader.py:4:1: F401 'pytest' imported but unused
./utils/log.py:196:5: E301 expected 1 blank line, found 0
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Requirements have changed. @seandst , @psav ?
*CFME QE Bot*

**Comment by seandst** [comment]
This has been linted, and properly rebased onto #1809 while I was in there.

**Comment by dajoRH** [comment]
Lint report for commit 807bf2fc7786fc898ebe6bafb624cdbf30a71b24:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
