### PR TITLE
New menu

### PR DESCRIPTION
**Pull request by psav**
{{pytest: cfme/tests/automate/test_instance.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 090644a2f25c57f988a5954892360b9c0b327424:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/sync_template_tracker.py:41:101: E501 line too long (120 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6c0bb337a736413fe0d65139fed9e55806d28d7a:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/sync_template_tracker.py:41:101: E501 line too long (120 > 100 characters)
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 58251a1aeb0f206e941a60285112fc5da269374b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 36cf691439188ee107edec8f50c509414339302d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8b5b86f0dc4b6016f6ce02ba54d2c474ef4508da:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef53a358889264db4b10e1fcb74fd40018c1da8e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Tested myself, looks quite good, merging then.

**Pull request merged**
