### PR TITLE
Added UI and DB validations on hawkular provider crud. Implemented clear_middleware_providers method.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 46781d7a48ca1f602ca1ffca809fa7bb33e793bf:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 57b82e9daaa14caaf19a6c6f66c77a3c07b855a1:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7c2fda4de9068ed66a42a02caa392c7f0567f6cf:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d61b2c178121f5b8f1e85e6d9c4d796817211395:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
@psav @mfalesni upstream test is pass.

**Pull request merged**
