### PR TITLE
Fix for 5.3

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/control/test_basic.py --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6a924e249ecf128f2bed53e4af8e2176dead3bed:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Looks pretty close, but PRT seems to think there's still a locator that isn't right. If that's unrelated or bogus, then :+1: to merge.

**Comment by mfalesni** [comment]
@seandst I did not notice those in PR Tester. Will fix.

**Comment by dajoRH** [comment]
Lint report for commit ea1af11f54a1c2e837cf04b4352fdaa763340cb1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c9e5bc6678057e61d7d46fffdf22b4f9eca2a3fd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b220fb1654a3d6a5e1a9115838c0a3fd71c725e2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
