### PR TITLE
UI coverage overhaul

### PR DESCRIPTION
**Pull request by seandst**
5 commits ><

{{pytest: -m smoke --ui-coverage}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8b2942c0f96e0fd99e92441ce0c2cddc75052765:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d6416138399ab875d8bed05296f4d0659b7f7237:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b59377cd9880888a2ef78851472a78ac4c717ed2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
PRT failure is a lie!

Two passed, which is cool, and the one that failed didn't fail as a result the coverage code. Most importantly, all three jobs reported their coverage numbers. :)

**Pull request merged**
