### PR TITLE
Adds install_munin method to appliance object

### PR DESCRIPTION
**Pull request by blrm**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e50e60ed964c336fff80ccad3704b8a45dd4bd99:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
This may need the new log_callback decorator thing in #2255, depending on what happens first ;)

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@blrm @psav aaaand, it happened first.

**Comment by psav** [comment]
I think we may move towards another more dynamic monitoring system for this @blrm what do you think? Can we close this off?

**Pull request closed without merging**
