### PR TITLE
Fix some CLI tests

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -k domain -v}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit a512a7afaea8489aca781c1726748f8d116bbe40:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e68acf4326ff1d3daf4521b418309f3bdedc7300:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Sorry I did a silly thing here.....I expected this to work with the appliances but sprout will need to rebuild them first I guess

**Comment by mfalesni** [comment]
@psav yup, sprout templates will have to be rebuilt if we want to use it again and correctly then.

**Comment by dajoRH** [comment]
Lint report for commit 0bd1d58401f9a496c620234b4998ad3cfd803864:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
