### PR TITLE
Refactoring of performance utils/fixtures and performance tests

### PR DESCRIPTION
**Pull request by akrzos**
Refactoring of the performance test code for eventually feature benchmarks.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8b297d6ccbb17f9e64d87a99d4930b52062ef904:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fc7ac55ccb8c95e3fa101222b54686eb03bb7a95:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a3b3a287ac5daf316c2676ea7de4f3b3d0be30c2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d464f01b3ded62c95d7a2c36c3591c7133d54dc3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34ed81a2f095e403067b47096295a2b856c42ec7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Lots of errors in the tester that I'm not sure are related to this PR, but there is one thing that you probably want to fix: 
```
UnboundLocalError: local variable 'links' referenced before assignment
utils/pagestats.py:150: UnboundLocalError
```

Looks like the exception is being thrown before 'links' is defined.

**Comment by dajoRH** [comment]
Lint report for commit 8e993e071a93f54d208f790317b40d95197d0b70:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by akrzos** [comment]
I addressed the UnboundLocalError.  The rest of the issues appear to be environmental or thresholds within the the UI perf tests exceeding, in that case it becomes subjective whether exceeding the threshold should be opened as a bug or adjustments should be made to the thresholds.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 93748587156c1fae77846cb12219e38754aec222:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./conftest.py:8:1: F401 'PIPE' imported but unused
./conftest.py:8:1: F401 'Popen' imported but unused
./conftest.py:11:1: F401 're' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d8aa3366dccfef90ce16ba1ff42f8ebbfd5aa676:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
