### PR TITLE
paginator: improve regexp

### PR DESCRIPTION
**Pull request by psav**
* Named groups
 * version.pick for regexp and controls
 * test_paginator: verify total number for paginator too

{{pytest: cfme/tests/automate/test_customization_paginator.py -v --long-running }}

### CODE REVIEW

**Comment by psav** [comment]
This is just a squash and slight tweak to #2505

**Comment by dajoRH** [comment]
Lint report for commit f0b6fe7afa9d5fe0aaa68953d8fb50581fcfb1ae:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3be147c3326dc216e682953d3ad22dbd0d40e2a2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Just fyi, in reports, there still is an old paginator, just in case you want to strip that support.

**Comment by psav** [comment]
#2512 replaces this

**Pull request closed without merging**
