### PR TITLE
Jenkins fixes

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/configure/test_access_control.py cfme/tests/automate/test_service_dialog.py cfme/tests/infrastructure/test_snapshot.py cfme/tests/configure/test_visual_cloud.py cfme/tests/configure/test_default_views_infra.py -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d3db1b9d544be797bb0f2789fce418e155a4f52b:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/infrastructure/provider.py:30:1: F401 'deferred_verpick' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 42257bbd2d06dc540bf0f277b483048109d695c7:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/infrastructure/provider.py:30:1: F401 'deferred_verpick' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 85d1cf4574b77de75998f968120866e4a7f0b4f6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
> Will be graudally adding commits for modules I fix

Ignorable thought: It would probably be easier to merge the changes as separate PRs for each fix.

**Comment by dajoRH** [comment]
Lint report for commit 2f5f3713f2b0df28dc89eabda0dac71b1eb1f3ad:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3b969d074d883caf859e9244bd0c21b9489c5fce:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/automate/explorer.py:140:19: E241 multiple spaces after ':'
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 14eb526282b4a74a53135a34d6729bbde6596116:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1e1c20486fc798775c2bc752950b0e9e584f2570:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Will cherry-pick commits.

**Pull request closed without merging**
