### PR TITLE
Revert "Select can eat just the name and create the XPath for it"

### PR DESCRIPTION
**Pull request by seandst**
Reverts RedHatQE/cfme_tests#1924

@mfalesni This was actually broken, according to the PR tester. Sorry. :)

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 891f6d6be005b69ca0b06c6789926ec92a97d048:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@seandst Yup, some multimethod weirdness I could not figure out, sorry for not having it as WIP :)

**Comment by mfalesni** [comment]
@seandst Saying that we should start cutting that out when we have time.

**Comment by psav** [comment]
I'm all for the removal too!

**Pull request merged**
