### PR TITLE
Add metadata to Sprout models

### PR DESCRIPTION
**Pull request by mfalesni**
Using metadata to store unmanaged templates for faster lookup and less provider load

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 875c3f84080944bd41722e44c890d90dc13938f5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9df9b2f0b8bd9dfcb280d30b370e552e33acbe45:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 33a513848405129258774b206caadd8c808912aa:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Merging this for myself.

**Pull request merged**
