### PR TITLE
Refactored Service Catalogs

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2117d35803bb9d867ac48ad01e4960632963fdfa:

`cfme/automate/service_dialogs.py`:
- :grey_exclamation: Line 147:47: **S001** *found %s formatter*

`cfme/fixtures/service_fixtures.py`:
- :heavy_exclamation_mark: Line 92:24: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34d600dc4e9c77f7dfa6f92241bce5ad8b0d1b84:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 732337dc05ccc69c46c07162e1bc3557e84a559e:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e8ddfc0d6ce9e8c246e448e71949172699ae8a3c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by sshveta** [comment]
vsphere 5.5 tests are failing because of error : Insufficient disk space on datastore 'cfme-esx-55-na01b'.')]

Please merge the PR .

**Comment by dajoRH** [comment]
Lint report for commit 9cd49fe22a316c5898373762160631815a7cbf3d:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c0b0ebe82d2b25623e91f66f843c3b9ae46cf8ce:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
