### PR TITLE
Initial Attempt.  It works.

### PR DESCRIPTION
**Pull request by jteehan**
Here's the first draft.  It works everytime and has decent error checking.  I tried it with all the common mistakes.  NOTE:  Requires the new mgmtsystem\scvmm.py and the pending cfme_data.yaml.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit dfd382147c22c1d65d57f7cf2b0b2e6c4c52683e:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_scvmm.py:69:13: E127 continuation line over-indented for visual indent
./scripts/template_upload_scvmm.py:142:43: W291 trailing whitespace
./scripts/template_upload_scvmm.py:143:41: W291 trailing whitespace
./scripts/template_upload_scvmm.py:144:39: W291 trailing whitespace
```
:trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@jteehan I think you'll have to get rid of the stale commits introduced probably by incorrect rebase.

**Comment by dajoRH** [comment]
Lint report for commit 479752cc5ff1e59c013f1fa947b07416cb749fcd:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_scvmm.py:66:17: E127 continuation line over-indented for visual indent
./scripts/template_upload_scvmm.py:85:1: W293 blank line contains whitespace
./scripts/template_upload_scvmm.py:131:1: W293 blank line contains whitespace
./scripts/template_upload_scvmm.py:135:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:135:15: E231 missing whitespace after ':'
./scripts/template_upload_scvmm.py:135:38: W291 trailing whitespace
./scripts/template_upload_scvmm.py:136:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:136:15: E231 missing whitespace after ':'
./scripts/template_upload_scvmm.py:136:36: W291 trailing whitespace
./scripts/template_upload_scvmm.py:137:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:137:15: E231 missing whitespace after ':'
./scripts/template_upload_scvmm.py:137:34: W291 trailing whitespace
./scripts/template_upload_scvmm.py:138:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:138:13: E231 missing whitespace after ':'
./scripts/template_upload_scvmm.py:148:1: W293 blank line contains whitespace
./scripts/template_upload_scvmm.py:155:1: W293 blank line contains whitespace
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d8549346df1098bba76dd7c245afcbabedc42b55:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_scvmm.py:66:13: E127 continuation line over-indented for visual indent
./scripts/template_upload_scvmm.py:135:43: W291 trailing whitespace
./scripts/template_upload_scvmm.py:136:41: W291 trailing whitespace
./scripts/template_upload_scvmm.py:137:39: W291 trailing whitespace
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fda02963b044ee7d7915b1a30e35f2964f775349:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_scvmm.py:68:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:68:12: E901 SyntaxError: invalid syntax
./scripts/template_upload_scvmm.py:69:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:71:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:72:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:73:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:74:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:75:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:76:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:79:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:80:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:81:5: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:84:1: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:87:8: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:87:10: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:93:13: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:93:15: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:99:1: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:100:16: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:100:18: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:110:37: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:110:39: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:114:25: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:114:27: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:119:1: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:121:13: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:121:15: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:122:18: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:122:20: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:123:10: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:123:12: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:126:9: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:126:11: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:128:28: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:128:30: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:130:28: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:130:30: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:132:19: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:132:21: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:134:15: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:134:17: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:139:5: E123 closing bracket does not match indentation of opening bracket's line
./scripts/template_upload_scvmm.py:140:11: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:140:13: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:142:8: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:142:10: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:145:22: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:145:24: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:147:26: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:147:28: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:152:16: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:152:18: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:154:20: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:154:22: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:159:17: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:159:19: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:161:16: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:161:18: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:162:16: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:162:18: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:163:10: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:163:12: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:164:8: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:164:10: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:184:13: E123 closing bracket does not match indentation of opening bracket's line
./scripts/template_upload_scvmm.py:189:1: E122 continuation line missing indentation or outdented
./scripts/template_upload_scvmm.py:191:9: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:191:11: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:193:11: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:193:13: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:195:17: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:195:19: E251 unexpected spaces around keyword / parameter equals
./scripts/template_upload_scvmm.py:198:1: E901 TokenError: EOF in multi-line statement
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit edf038b22019e2d8d5188415ed7dc5cac62f033b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
