### PR TITLE
Rather use 'default' Analysis Profile

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3084c168efde26f0ec0c1f9806af21d54c236d1e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ae2b02d50929e38cb4bbb61e5ccae67ceadccf0e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 43d00a6f27fc79e0c3161de82fced824f3325d1d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1326cd1731aa57018b70c1e1408cb637cb94d11f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef5e22f94916518d0cb8c0688380b74f8591a04d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 19213f2725f6d94ca8caacc6ae249d2933339bc8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Looks alright, but I think you can squash everything up into the first commit

**Comment by dajoRH** [comment]
Lint report for commit 2976ad5988ca8ac9ea23cec48b09cd14f953ea7c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I gave up on file creation checking, I will just use existing files for file fleecing.

**Comment by dajoRH** [comment]
Lint report for commit afd5524b020ade33853b5e15cf74ad530e1c44c7:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/control/test_compliance.py:3:1: F401 'time' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 70d98a64d733d34d3480c097963ed4cab3f671b3:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
