### PR TITLE
When unknown_unknown file faced, it is captured in logs

### PR DESCRIPTION
**Pull request by mfalesni**
I also improved the test by adding soft asserts and more verbose error logging since that was not touched for ages.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 5e58d35a12aa2195537f1809aee9b22a756dde4a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav @seandst This is ok to merge if you have nothing against the method of collecting the file.

**Comment by dajoRH** [comment]
Lint report for commit 4244bd164f8979c0ab22e8b291a9cd2070e039f9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 27107b89c0bd373eea0f797a813303304eacad19:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Just trying to understand, what could these bad files be?

**Comment by mfalesni** [comment]
@psav It appears that in some occasions the datetime for the archive file is unspecified. This saves the file for further examination.

**Comment by psav** [comment]
Would it be better to capture this with artifactor so it gets stored with the test?

**Comment by mfalesni** [comment]
@psav It would currently require loading the file in the memory which I consider a bit unsafe since the size can vary greatly. Maybe the filedump hook could be extended so it could return a resulting filename to you and then I could just download the file on that name.

**Comment by dajohnso** [comment]
@mfalesni whats the latest here, is this enough to merge with a card for future improvements?

**Comment by mfalesni** [comment]
@dajohnso @psav Last time it ran it worked so there is no reason not to merge.

**Comment by dajoRH** [comment]
Lint report for commit 9b35a832037055b822ae2f8bf4a633874adf549f:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 76c7bcf34cfea9a160546aeb2d0290bdb2c98df8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7cf333df74613295817da75cd301b8b22f8e55c5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b1af9d1f561d8e6f898c86e28b5054a0a0d06a41:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e08318e1c72ccf32966f2367b5cbc795eeba1265:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
