### PR TITLE
Update blocker div locator for force_navigate

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -v -k search --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1481efea02fe6dc27f426c277fd9c43d8393dd40:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
for information, this is to protect from stale notification div that blocks whole page

**Comment by dajoRH** [comment]
Lint report for commit 42d35f0c77bf8e46925c56c0eaa12a59071c0b8b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
PRT revealed a few new locator issues, but I don't see anything about the blocker div, so :+1:

**Comment by mfalesni** [comment]
@seandst Yea, that are advanced search issues in general.

**Pull request merged**
