### PR TITLE
[WIP][NO TEST] Sprout tweaks with updates

### PR DESCRIPTION
**Pull request by mfalesni**
A possibility to do yum updates was requested. I however need to do some things in advance in order to integrate the yum updater. Plus I added a nicer user selector and reworked the links that should now be more REST-ish.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 0143b3a55af5261af09beab0c3ae4e6f51ea98cd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0452070e0dcbc63e3e1c53d04ac551dfea69ce5b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 140a5bf830a0634c86b7344aed7ef6a884ae5ecf:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e53cf4710aa0633bdd52ed2d9aad14d845213b2c:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Merging. If problems, then I will try to troubleshoot them.

**Pull request merged**
