### PR TITLE
change the stream to be inline with trackerbot & cfme-data

### PR DESCRIPTION
**Pull request by amavinag**
* pick the stream from cfme-data, the cfme-data is updated
    with the stream names same as in trackerbot.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 678f293ce03dda514714a54a991f85978d050961:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Does this require a change to cfme_data.yaml? Did we do any analysis to see if anything else is impacted by this?

**Comment by amavinag** [comment]
@psav: Yes, this requires changes to cfme_data. the image url's from cfme_data are being used by uploader scripts (which iterate through the urls's and not dependent on names) and are not affected by this change.

is there any other area/script fetching url names?

**Comment by psav** [comment]
I'm not aware of any, @mfalesni @jkrocil ???

**Comment by mfalesni** [comment]
@psav me neither

**Pull request merged**
