### PR TITLE
Fix Input locator in Service Catalogs

### PR DESCRIPTION
**Pull request by sshveta**
{{pytest: -v -k 'service_catalog' --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4e4fd8c63c8ec571a701ad8a782bd36c9fbeab01:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./conftest.py:11:1: F401 'AuthSetting' imported but unused
```
*CFME QE Bot*

**Comment by sshveta** [comment]
{{pytest: -v -k 'service_catalog' --long-running}}

**Comment by dajoRH** [comment]
Lint report for commit 39b9293028edf064230198b73880c4410aa06509:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
@sshveta The {{metadata}} has to be in the description of the PR, not in a comment

**Comment by dajoRH** [comment]
Lint report for commit 23e3a39bd8056d2511a146b3bc075115df923b4e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
