### PR TITLE
Handle empty collection Issue

### PR DESCRIPTION
**Pull request by anewmanRH**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 19252a57ddd2084349ecb28c059cf9b5f6f73de3:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Well, I think that the more pythonic way is to try/except :)

**Comment by psav** [comment]
@mfalesni interesting. I would have said that having a zero length list here would be something that was reasonably expected. As such I opted for that approach, but I bow to the experts ;)

**Comment by mfalesni** [comment]
It comes to the fact that you could do eg.:
```python
try:
    col[0].action.refresh()
except IndexError:
    # complain the col is empty
except AttributeError:
    # complain the .refresh method is not present (as .action is always present)
```

(if you wanted, of course)

**Pull request merged**
