### PR TITLE
Fixed ssh closing a second time

### PR DESCRIPTION
**Pull request by psav**
Fixed ssh closing a second time

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b847cf568474c87fb0e6c4942c649dd372b4c335:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 318902da5f39051d0eb0b587b7e3a311d5c23e6a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
@seandst What do yo uwant to do with this one? Close it off in favor of a better memoized SSHclient?

**Comment by seandst** [comment]
This was already merged. :)

When I made the memoized sshclient, I stacked the commit on top of this PR, so that if I needed to revert it (and sadly I did) we'd still have your fix in place.

Not sure why github thinks this hasn't been merged, I must've thrown in a rebase without thinking.

**Pull request closed without merging**
