### PR TITLE
Test default items per page for reports

### PR DESCRIPTION
**Pull request by akarol**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1806e67711f2e8cf8c31f908f84492abd588b3af:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
I've re-ran the PR tester to see if the 5.4 errors were random or bugs.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bbb505a7d552dfd6a66591a9e7489fe8daac8352:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 445a6db2ecf4640e7afe84fc6bdac79efcb0d537:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
