### PR TITLE
Fix provider crud in 55 and 56

### PR DESCRIPTION
**Pull request by jkrocil**
Fix services menu in 56

{{pytest: -k "test_provider_crud and not edit and not rest" --use-provider complete }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3df799acec649bc377297ca75dcdc969d4ca2e8f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
Containers fail in 5.6 is expected (openshift server has 10 containers, CFME sees 5; I believe that's a bug in CFME, didn't have the time to investigate yet).
rhos6-ga-ssl fail is expected as well (something is up with it, ConnectionRefused errors).

**Comment by dajoRH** [comment]
Lint report for commit 686c995deea2b2d41d0773b83a5adee4258e9b88:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
Conatiners fail is known, being investigated.
vSphere 5 fail is known - mgmtsystem fix provided by @psav.
rhevm35-nested fail is being investigated, not caused by this PR. (happens when rhevm provider has no candu creds in the yaml)

**Pull request merged**
