### PR TITLE
scpexception in conftest doesn't break every test

### PR DESCRIPTION
**Pull request by seandst**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 00a48663d5adb776ee04cc442712a7d93f0b0636:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
So, if we are unable to set it, what happens? We just run with it like it is?

**Comment by seandst** [comment]
Yep. A better fix for the SCP issues is forthcoming, this is just crappy bandaid.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by seandst** [comment]
https://github.com/RedHatQE/cfme_tests/commit/5c9733c846c2a781130303c48831fb645f268630

**Pull request closed without merging**
