### PR TITLE
Update providers.py

### PR DESCRIPTION
**Pull request by rrasouli**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fe01720f01282f092ff51ce55f9d3e133bd7678e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@rrasouli I see PR tester complaining about "Bad sig". Did you use `-S` option? If not, you can amend the last commit and repush like this one:

```bash
git checkout patch-1
git commit -S --amend  # An editor pops up to change the commit message, save that and then enter hte passphrase
git push origin patch-1 --force   # Force since the hash has changed with the signature.
```

To verify the signature, you should do `git log --show-signature` and you should see something like this (of course with your name/GPG ID):

```
commit 418284b98cf7d7be7b795b22d2e01c851c36d121
gpg: Signature made Mon 25 Jan 2016 10:30:10 AM CET using RSA key ID 7EBCD0CB
gpg: Good signature from "Milan Falesnik <milan@falesnik.net>"
gpg:                 aka "Milan Falesnik <mfalesni@redhat.com>"
gpg:                 aka "[jpeg image of size 2472]"
Author: Milan Falešník <mfalesni@redhat.com>
Date:   Mon Jan 25 10:26:30 2016 +0100

    Sprout - Fix 500 and mute emails till the solution is found
    
    * Template deletion suggester kept spamming on version.
    * django_object_actions apparently does not work entirely properly with newer admin, Groups were throwing 500.

```

**Comment by mfalesni** [comment]
It is also worth mentioning that this PR requires #2599 to be merged first otherwise this factory will pass a yet-unknown parameter sec_protocol into the `OpenstackInfraProvider` constructor.

Apart from the signature and the dependency, the code change is good.

**Comment by mfalesni** [comment]
Or you can just cherry-pick 05f965b from #2599 to this pull request and close #2599 . Or rebase this branch over your `osinfra_security` branch containing the initial osinfra sec_protocol changes and 2599 will get closed automatically once this PR is merged.

**Comment by dajoRH** [comment]
Lint report for commit 21033022f430a82c2616a1c6aaed4b14aa3a421a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Looks good, merging.

**Pull request merged**
