### PR TITLE
Cached property

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 0892760423a6e9fa89902b6a93fb9191029734cf:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/web_ui/__init__.py:346:5: E303 too many blank lines (3)
./cfme/web_ui/__init__.py:352:5: E303 too many blank lines (3)
./utils/__init__.py:8:1: F401 'cached_property' imported but unused
./utils/__init__.py:12:1: E303 too many blank lines (3)
```
:trollface:
*CFME QE Bot*

**Comment by psav** [comment]
I know I asked this already, but just checking, are all the ```del``` statements compatible here?

**Comment by RonnyPfannschmidt** [comment]
yes, non data properties work by giving the instance attribute precedence,
thus they are quicker and compatible to del usage

**Comment by dajoRH** [comment]
Lint report for commit 339eceb58b680338343aa313b5900b599fd4981e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9174be47bcbe14d7c3932a3b94c2240aaee9abaa:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 64619738cce59311f19a95d5d84b3d0fa9f4cd9d:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 64b384f7c32efe608715cf99167c37840b7fb4b8:

`cfme/configure/configuration/__init__.py`:
- File lint OK :cake: :punch: :cookie:

`cfme/infrastructure/config_management.py`:
- File lint OK :cake: :punch: :cookie:

`cfme/intelligence/reports/reports.py`:
- File lint OK :cake: :punch: :cookie:

`cfme/intelligence/reports/ui_elements.py`:
- File lint OK :cake: :punch: :cookie:

`cfme/web_ui/__init__.py`:
- File lint OK :cake: :punch: :cookie:

`fixtures/events.py`:
- File lint OK :cake: :punch: :cookie:

`fixtures/pytest_store.py`:
- File lint OK :cake: :punch: :cookie:

`utils/__init__.py`:
- File lint OK :cake: :punch: :cookie:

`utils/appliance.py`:
- File lint OK :cake: :punch: :cookie:

`utils/bz.py`:
- File lint OK :cake: :punch: :cookie:

`utils/db.py`:
- File lint OK :cake: :punch: :cookie:

`utils/log.py`:
- File lint OK :cake: :punch: :cookie:

`utils/miq_soap.py`:
- File lint OK :cake: :punch: :cookie:

`utils/snmp_client.py`:
- :red_circle: Line 10:1: **F401** *'cached_property' imported but unused*

`utils/tests/test_lazycache.py`:
- File lint OK :cake: :punch: :cookie:

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f9bc745a401d4ee9606aa1d49b52715d3c0f9ed2:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
