### PR TITLE
[WIP] Add BZ in log collection, remove fixed old ones

### PR DESCRIPTION
**Pull request by jkrocil**
The new bug https://bugzilla.redhat.com/show_bug.cgi?id=1184465

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9e7e6af580fea8b8f27902d9e0f088184a619a45:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0d46b51037542523e2f8c2ef9c4acc46cd2c06cf:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
Also added https://bugzilla.redhat.com/show_bug.cgi?id=1186336 which makes it skip SMB and FTP on upstream (NFS is ok).

**Comment by psav** [comment]
Is this still WIP?

**Comment by jkrocil** [comment]
Yep, still WIP - waiting for #1570. Then I'll have to move a BZ issue to GH (because it's upstream only) and change the markers..

**Comment by dajoRH** [comment]
Lint report for commit a5c6460f4a86e11656b27819e7b2f9678d42e5ed:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please?
*CFME QE Bot*

**Pull request closed without merging**
