### PR TITLE
Group and Users rest collection

### PR DESCRIPTION
**Pull request by lehinevych**
{{pytest: cfme/tests/configure/test_rest_access_control.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d65bfe9ac0edd4906b1ec5ce3b722fd2e55c0543:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/rest/__init__.py:266:1: E303 too many blank lines (3)
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit df8341fe9e5b50fff63b2b8b2dbc09d14b7f6210:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fee30fc05c1cc6f83aa4e34bcc60ae32f5419196:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cc0335ab3a136d7db54538899bc49dfa0205c985:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/configure/test_rest_access_control.py:12:1: F401 'appliance_is_downstream' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d724028da7579bc883fe0e1c5ae4516df7d911d8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34c4280e862247331565c9b97afa3a80e981fead:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 08cbcf9378c425ae4e992b05408a273bdd84eab2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by lehinevych** [comment]
Should skip on 5.5 because these group and user methods are available only for upstream.

**Comment by dajoRH** [comment]
Lint report for commit d3c8735fcda890c021a8d78407d237c883b15c78:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
