### PR TITLE
Fix ui coverage in 5.5

### PR DESCRIPTION
**Pull request by jkrocil**
`appliance_console/env` is no longer available; I had to switch it to LinuxAdmin instead to obtain the appliance's IP. In addition, the coverage hook file itself is now not touched by the `thing_toucher` - this is just a minor enhancement.

{{pytest: -k test_login -v --ui-coverage}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit bd9bac7435cfd1c8f35b225f53e92bc3e826f13b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
It's not collecting for some reason so... that's a separate issue I'm looking into now.

**Comment by dajoRH** [comment]
Lint report for commit 9e53f081b61492c5814b25524cb6da0be9609772:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 213687d9cdf7e18c7529ee4ce2abc3b134d39538:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by jkrocil** [comment]
Upstream failure `INTERNALERROR> Exception: SSH connection to 10.8.199.115:22 failed, port unavailable` not caused by this PR.

**Comment by jkrocil** [comment]
55z is currently stuck at `Appliance pool 20296. Waiting for fulfillment ...` and has been that way for some time. Again - not caused by this PR.

**Comment by mfalesni** [comment]
Looks green and legit.

**Comment by psav** [comment]
Agreed!

**Pull request merged**
