### PR TITLE
Jenkins fixes

### PR DESCRIPTION
**Pull request by mfalesni**
* Fix host advanced search tests for the Host/Node change
* Do not move on option,, move to parent select instead.
* Try hardening the template selection for provisioning

{{pytest: -v -k "test_advanced_search_host or test_widgets_on_dashboard or test_copy_request " --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9aa359f341e9da62ad1af07d5f79a0b6ec19660d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a77b456f749fdfbcd975c3e78d1093ea13070128:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ac42a0deee1dd54d72936e07e7770a34070fe123:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 23382559955abbbbcc340e3a55a0f207968356a8:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 54ab35d45d7b67e83d7404386c420fe4ff6120dd:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/services/requests.py:5:1: F401 'form_buttons' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b0ea1675efefd679ed0316132c2461e48f42b4aa:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/services/requests.py:5:1: F401 'form_buttons' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e548acf3953337168e82a8dcd089fd49bdb1d3c5:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
So, the 5.3 errors are from BZ'd tests, not exactly sure why they are unblocked but never mind that. 5.4 is clean, which is amazing. Upstream has one error from shveta's test and one sporadic filtering error from me. I am merging this.

**Pull request merged**
