### PR TITLE
Update FormButtons

### PR DESCRIPTION
**Pull request by mfalesni**
Closes #2235

I want to let it test on some crud things.

{{pytest: -v -m crud --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 90a7d6cf05f8efd360d927c62975f5746f78f7bc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
This is heroic.

**Comment by mfalesni** [comment]
Meh, some 5.4 problems now it seems. Will fix it

**Comment by dajoRH** [comment]
Lint report for commit f58088427b437f4e9bb68bde66713559dd58205d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav said merge it, so merging it.

**Pull request merged**
