### PR TITLE
Ensure VM analysis REST client is from the current appliance.

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/infrastructure/test_vm_analysis.py -v -k REST --use-provider vsphere55 --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f80c367733040fdd3179a7616eb30400e5725511:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c92173dc11f3fcfc29062a395a7ff650de0e5816:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
This looked good on PR tester. I just had to exclude the tests for 5.3 and lower.

**Comment by dajoRH** [comment]
Lint report for commit 864fdf94b21297adec352727f976cd35a6d281f9:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 486f348703ff9d25aad1a59f093331f4441950fd:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
