### PR TITLE
Add Hawkular provider 3

### PR DESCRIPTION
**Pull request by vnugent**
Add Hawkular provider support with improvements from psav and mfalesni
Account for discrepancy in Provider/Manager wording https://issues.jboss.org/browse/HAWKULAR-1062
supersedes PR https://github.com/RedHatQE/cfme_tests/pull/2849

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6d15d586fea1ccc60bbe3a7cde9d172b47a8c13f:

`cfme/common/provider.py`:
- :bangbang: Line 196:101: **E501** *line too long (115 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dd3c58d26d5710518e56e0020188181b65f6611f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Can you sign the commit :)

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
Closed by #2860

**Pull request closed without merging**
