### PR TITLE
Reconfigure service test

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 7c270f6d84edf1fa55cefb119f2cfca7c079a096:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a23cb91aa3740faef8f4530f1fd87cd8e1d986b6:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3fedbbe749293132a9f2132340c8962ccfddd861:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8846781f27e4fc40c9a8b52ade7d1e2266abace4:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Did not run on upstream and 5.3 but given that it passed on 5.4, I believe it is ok to merge.

**Pull request merged**
