### PR TITLE
Fix version pick on import + lint

### PR DESCRIPTION
**Pull request by jkrocil**

### CODE REVIEW

**Comment by mfalesni** [comment]
Lint report for commit e2aa7502bfc4c08716bb51e7d30bc019bf14bf99:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./artifactor/plugins/reporter.py:129:63: E901 SyntaxError: invalid syntax
./markers/stream_excluder.py:19:64: E901 SyntaxError: invalid syntax
./markers/uses.py:36:15: E901 SyntaxError: invalid syntax
./cfme/intelligence/reports/dashboards.py:88:22: E901 SyntaxError: invalid syntax
./cfme/web_ui/expression_editor.py:360:32: E901 SyntaxError: invalid syntax
./cfme/web_ui/flash.py:156:55: E901 SyntaxError: invalid syntax
./cfme/control/explorer.py:821:49: E901 SyntaxError: invalid syntax
./cfme/web_ui/tabstrip.py:70:41: E901 SyntaxError: invalid syntax
./cfme/web_ui/__init__.py:321:74: E901 SyntaxError: invalid syntax
./cfme/automate/provisioning_dialogs.py:92:37: E901 SyntaxError: invalid syntax
./cfme/configure/red_hat_updates.py:227:56: E901 SyntaxError: invalid syntax
./cfme/tests/test_rest.py:63:44: E901 SyntaxError: invalid syntax
./cfme/tests/intelligence/test_dashboard.py:65:32: E901 SyntaxError: invalid syntax
./cfme/tests/intelligence/reports/test_canned_corresponds.py:24:65: E901 SyntaxError: invalid syntax
./cfme/configure/configuration/__init__.py:1279:37: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_cloud_init_provisioning.py:35:31: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_genealogy.py:28:28: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_host_provisioning.py:37:30: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_provisioning.py:33:28: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_iso_provisioning.py:38:32: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_retirement.py:25:28: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_provisioning_dialog.py:49:28: E901 SyntaxError: invalid syntax
./cfme/tests/infrastructure/test_pxe_provisioning.py:35:32: E901 SyntaxError: invalid syntax
./cfme/tests/services/test_add_remove_vm_to_service.py:66:28: E901 SyntaxError: invalid syntax
./cfme/tests/services/test_cloud_service_catalogs.py:36:25: E901 SyntaxError: invalid syntax
./cfme/tests/services/test_iso_service_catalogs.py:41:32: E901 SyntaxError: invalid syntax
./cfme/tests/services/test_myservice.py:40:28: E901 SyntaxError: invalid syntax
./cfme/tests/cloud/test_cloud_init_provisioning.py:31:31: E901 SyntaxError: invalid syntax
./cfme/tests/services/test_service_catalogs.py:39:28: E901 SyntaxError: invalid syntax
./cfme/tests/services/test_pxe_service_catalogs.py:39:32: E901 SyntaxError: invalid syntax
./cfme/tests/cloud/test_provisioning.py:29:25: E901 SyntaxError: invalid syntax
./cfme/tests/automate/test_common_methods.py:34:28: E901 SyntaxError: invalid syntax
./cfme/tests/configure/test_log_depot_operation.py:230:36: E901 SyntaxError: invalid syntax
./fixtures/browser.py:10:31: E901 SyntaxError: invalid syntax
./fixtures/events.py:158:31: E901 SyntaxError: invalid syntax
./scripts/appliance_spring.py:144:52: E901 SyntaxError: invalid syntax
./fixtures/parallelizer/remote.py:68:49: E901 SyntaxError: invalid syntax
./scripts/dockerbot/check_prs.py:126:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:127:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:128:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:134:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:136:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:137:17: E265 block comment should start with '# '
./metaplugins/server_roles.py:51:32: E901 SyntaxError: invalid syntax
./scripts/dockerbot/dockerbot.py:18:31: E901 SyntaxError: invalid syntax
./sprout/appliances/models.py:354:52: E901 SyntaxError: invalid syntax
./sprout/appliances/views.py:318:62: E901 SyntaxError: invalid syntax
./utils/db.py:311:46: E901 SyntaxError: invalid syntax
./utils/bz.py:10:22: E901 SyntaxError: invalid syntax
./utils/events.py:152:54: E901 SyntaxError: invalid syntax
./utils/randomness.py:98:46: E901 SyntaxError: invalid syntax
./utils/testgen.py:255:56: E901 SyntaxError: invalid syntax
./utils/version.py:82:36: E901 SyntaxError: invalid syntax
./utils/mgmt_system.py:341:60: E901 SyntaxError: invalid syntax
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e2aa7502bfc4c08716bb51e7d30bc019bf14bf99:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/dockerbot/check_prs.py:126:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:127:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:128:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:134:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:136:17: E265 block comment should start with '# '
./scripts/dockerbot/check_prs.py:137:17: E265 block comment should start with '# '
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a290a37253491cf481c3dec7d964a39672db398e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7aa6b3236f0020f54a1da7ff018dddd3b014c582:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
