### PR TITLE
Angular Select + Inputs

### PR DESCRIPTION
**Pull request by psav**
{{pytest: -k test_provider_crud}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit cc194cba68f9dbf196b545a87cca4101d7093f50:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/infrastructure/provider.py:21:1: F401 'SuperSelect' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 873df6e4b9f8948170ad76df1f051f07fb58cbb1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit afe89e93ed6bacca2338e10278ad5fdf60f5e650:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit afcd734804fb340c42ecfeb4195d156e7ed1c989:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/infrastructure/provider.py:30:1: F401 'deferred_verpick' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 53c7664513a775148ff9c8c2b9eb22e8fb02cf0c:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/infrastructure/provider.py:30:1: F401 'deferred_verpick' imported but unused
```
:trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
Oh, lint problem intriduced ot master, aiee.

**Pull request merged**
