### PR TITLE
Disable autofocus in Firefox

### PR DESCRIPTION
**Pull request by mfalesni**
Autofocus, I command you to go away!

{{pytest: cfme/tests/infrastructure/test_host_analysis.py -v }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d8e15ea589ab057b5f24cc2cb7da48ed36d7b42e:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Suggest we close this now that we have a more generic solution?

**Comment by mfalesni** [comment]
@psav well I guess having this in the profile could be a safety measure ...

**Comment by jkrocil** [comment]
The merged PR doesn't modify behavior.
This one does.
I'm not sure what's gonna happen when miq javascript can't access focus of elements. Do you? Is there a possibility of errors in js console and infinite loops? (I'm asking because I seriously have no idea how this would alter the behavior)

**Comment by mfalesni** [comment]
@jkrocil http://forums.mozillazine.org/viewtopic.php?f=7&p=5959775

**Comment by psav** [comment]
I think I'm in favor of closing this one off for now, it's Firefox only anyway which to me means that we are not testing all browsers in the same way.

**Pull request closed without merging**
