### PR TITLE
[WIP] : Automate 1223911

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d605cc9abafb83a11bdf04856e4da4dba222797d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b1b0f3feb0d85a0cdfe094fdfe2f28c3a46af241:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Any movement on this on @sshveta? It didn't go through PRT yet, is it ready for review?

**Comment by sshveta** [comment]
I was stuck on something i think . will check again and let u know by EOD

**Comment by sshveta** [comment]
Closing this one . Opened a new PR -2696

**Pull request closed without merging**
