### PR TITLE
Snapshot flash messages fixed

### PR DESCRIPTION
**Pull request by mfalesni**
+ flash messages now only read the visible elements and to be sure, elements() does not fail when empty list passed.

{{pytest: cfme/tests/infrastructure/test_snapshot.py -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d88caab0bc6fa3da2c0cb28552c1d9871ea83fa2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5823378a4ec01176f4c0b13b4cb718c39a78a77d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
The error that is there will be fixed by another PR (#2273)

**Comment by dajoRH** [comment]
Lint report for commit 228dad6ef738b1a2117b6420d2c5ac1eaf7db86a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
