### PR TITLE
renamed test_provider_crud.py to test_middleware_provider.py

### PR DESCRIPTION
**Pull request by amavinag**
* renamed the file cfme/tests/middleware/test_provider_crud.py
    to cfme/tests/middleware/test_middleware_provider.py

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 262aa2a77597ee374ecd05b59ad08154cd82a4e9:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajohnso** [comment]
@amavinag where was this causing issues?  Just curious

**Comment by dajohnso** [comment]
@amavinag , so yeah, this is screwing up the template tester, @psav , would a better fix be to remove smoke?  Merging for now but we just discuss how to proceed around this.  See
https://<jenkins>/view/Template_tester/job/template-tester-virtualcenter/764/console

**Comment by amavinag** [comment]
@dajohnso : I think, this is not a smoke test. it erred while pytest test discovery due to duplicate file names.

**Pull request merged**
