### PR TITLE
utils/providers.py: Enable embedded credentials

### PR DESCRIPTION
**Pull request by mfalesni**
This will be useful in some CI setups that will require generating provider data based on the environment. With this extension, it will be possible to just place credentials in the cfme_data yaml, which will make the conf setup simple, just generate cfme_data.local.yaml. So these alternatives are possible right now:

```yaml
management_systems:
    provider_key:
        credentials: mycredentials  # Which will retrieve them from credentials.(e)yaml
```

Or:

```yaml
management_systems:
    provider_key:
        credentials:
            username: foo
            password: bar  # Credentials specified directly in the cfme_data
```

It should work for all credentials keys inside the provider's definition, I think I've replaced all the function calls that resolve it.

@rrasouli This might help you in your setup, you can make a script that will read the `stackrc` and `overcloudrc` (or whatever the files are) and then emit a yaml which would be stored as `cfme_data.local.yaml` without bothering with encrypted credentials and stuff.

{{pytest: -m crud}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4d0b56e6471d55b32ad9839b828634b0ec787518:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav ^^^

**Comment by mfalesni** [comment]
Tests look good, only repositories are failing when looking at 5.5.

**Comment by psav** [comment]
Is this going to encourage bad behaviours to slip in?

**Comment by mfalesni** [comment]
@psav That is on reviewers to catch it. It should be reiterated that this is designed to handle specific non-standard situations for testing environments, to make them easier to do and not to make someone's life easier by not putting credentials of a stable env to credentials eyaml.

**Comment by mfalesni** [comment]
And I reiterate:

**THIS IS NOT DESIGNED TO BE USED UNDER NORMAL CONDITIONS**

So under ordinary circumstances and ordinary setup, you cannot use this feature.

This functionality is designed to be used when the environment for testing is generated dynamically, like TripleO.

**Pull request merged**
