### PR TITLE
Initial commit of workers analysis including top_ouput cpu/memory to queue test.

### PR DESCRIPTION
**Pull request by akrzos**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ebad5bd7bc4cf23c9331534beb7bfee8bf80a6e5:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./cfme/tests/perf/queue/test_queue.py:67:74: E203 whitespace before ','
./utils/perf_message_stats.py:42:101: E501 line too long (137 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8cba044931fcd0c5983059a02efa4c548e7678f9:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./utils/perf_message_stats.py:42:101: E501 line too long (137 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 82bf2e5b28acca2643f4f2bd6a0ce6a25dd2c74f:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./utils/perf_message_stats.py:56:29: F821 undefined name 'files'
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 49a71ad4431047a931f7ce7aa6951e184c855b37:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./utils/perf_message_stats.py:198:101: E501 line too long (114 > 100 characters)
```
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1002144676e55447561260842a319340463c2141:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 210446dae3d0e963818f75080825763a932d8069:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by akrzos** [comment]
This adds worker CPU/Memory charts and tracks workers that have exceeded memory/uptime or have exited or been interrupted as reported by the evm log file and top log file.

**Comment by dajoRH** [comment]
Lint report for commit 0e312d02b525191df7c1f066e3605dd9a4c5a73b:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b67463b59aadc54abc913965cf21e3c930f52d15:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
