### PR TITLE
Fix paginator

### PR DESCRIPTION
**Pull request by mfalesni**
However I am not sure if this would be the best solution since the rec_total gets easily confused with rec_end now ...

{{pytest: cfme/tests/automate/test_customization_paginator.py -v --long-running }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit db87e943a45c268d1a74af37ee28d6b7401f2571:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav ? ^

**Comment by psav** [comment]
@mfalesni and I discussed this and I think we are in agreement that we should just rewrite the regexp for the whole module.

**Comment by psav** [comment]
This is superseded by #2505

**Pull request closed without merging**
