### PR TITLE
Browser open method added

### PR DESCRIPTION
**Pull request by sshveta**
To ensure that browser is opened before tests

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit dd69ea451793cd6475a0c0e41a133ea391192e0c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
So, the fix fixes the problem with the browser() being None but there are errors on service provisionings ...

**Comment by dajoRH** [comment]
Lint report for commit 77261def3df6eca5801a10dd83327ad168a4463b:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
Good.

**Pull request merged**
