### PR TITLE
Fix OpenStack AMQP

### PR DESCRIPTION
**Pull request by psav**
{{pytest: -k test_provider_crud --use-provider=rhos7-ga}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 56c4720823af861daed68dff16be3228b0172b6a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 136b1c4558f6b0a792334b68d8e82a0d41417652:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1cd3d4c6c24a71853ad30549959711c7783ba3cc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
Do you think we could keep only the newer locators in `properties_form_56`? Not directly related to the PR (we can have a separate one for it) but would be nice to have. https://github.com/RedHatQE/cfme_tests/pull/2980/files#diff-ebf0b1c739c9e0bf1e5e4bdbbb8651faR66

**Comment by psav** [comment]
Agreed!

**Comment by dajoRH** [comment]
Lint report for commit 696aa574c2868a72548316149782841feebd4f6d:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
Issues are unrelated; rhos setup passed on 56.

**Pull request merged**
