### PR TITLE
[NO TEST] Script to show all API calls

### PR DESCRIPTION
**Pull request by mfalesni**
I've been using this script for some time and did not realize it is not in the repository yet :)

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ee02567b865ed6e1dd8ad66cb378785aa305fa73:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by seandst** [comment]
Is this actually WIP, then? If not, remove the label.

**Comment by mfalesni** [comment]
@seandst it is WIP NO TEST as eg. Sprout because there is no point of testing this in the pytest run.

**Comment by seandst** [comment]
WIP means WIP. If it isn't WIP, then please remove the label. The "WIP NO TEST" convention is a misleading abuse of the WIP tag, and needs to be abolished.

**Comment by psav** [comment]
I am responsible.....I will fix soon....... *wades through syrup*

**Comment by mfalesni** [comment]
Bad psav, bad.

**Comment by seandst** [comment]
FOR SHAME.

**Pull request merged**
