### PR TITLE
Added scvmm details and regex

### PR DESCRIPTION
**Pull request by jteehan**
Blair should probably look over this as well.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e3303977566734d30f124cd614bd6f2d74cce66f:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_all.py:164:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4bbab546440ea21175e89d8b1359d6f13be74614:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_all.py:226:3: E227 missing whitespace around bitwise or shift operator
./scripts/template_upload_all.py:226:3: E901 SyntaxError: invalid syntax
./scripts/template_upload_all.py:226:7: E225 missing whitespace around operator
./scripts/template_upload_all.py:227:5: E113 unexpected indentation
./scripts/template_upload_all.py:229:3: E225 missing whitespace around operator
./scripts/template_upload_all.py:229:5: E225 missing whitespace around operator
./scripts/template_upload_all.py:229:7: E225 missing whitespace around operator
./scripts/template_upload_all.py:230:5: E113 unexpected indentation
./scripts/template_upload_all.py:232:7: E225 missing whitespace around operator
./scripts/template_upload_all.py:233:5: E113 unexpected indentation
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2d1ab98387156a3acfec7d39be6f381fc7e6b12a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Just needs a good squashing, but gets a +1 from me, I'll leave @blrm to give it a look and if he's happy we'll green it up :)

**Comment by jteehan** [comment]
I tried to squash it but there were other commits in the list that weren't mine and I didn't know how to resolve them.

**Comment by psav** [comment]
If your branch is the same as it is now (if not you should be able to do
git reset --hard origin/localjt)
then you can do
git checkout master
git pull upstream master
git checkout localjt
git rebase master
git rebase -i master
(squash away)
git push origin localjt -f

That should do it

**Comment by dajoRH** [comment]
Lint report for commit 285dc621574fe24feae7e12ec9667648a1839024:
:hurtrealbad: There were some flake issues that need to be resolved in order to merge the pull request:
```
./scripts/template_upload_all.py:164:1: E302 expected 2 blank lines, found 1
```
:trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d4996a01c08ff5fcba7bac801781e534c1b9287a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by blrm** [comment]
This looks good! Thanks for adding it @jteehan

**Pull request merged**
