### PR TITLE
remove bz blockers for filter test cases

### PR DESCRIPTION
**Pull request by akarol**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f12ea206823d81e0ef23064c2d6b0833be55494e:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
I still see some failures here...

**Comment by dajoRH** [comment]
Lint report for commit 38dfc98c3d7e04ae836af1f4787e0e6660a1d41a:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 11b9512fbf40d63940842bbe04b7d21130b14b2d:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Pull request merged**
