### PR TITLE
Cleanup logging in virtual_machines.py

### PR DESCRIPTION
**Pull request by mfalesni**
There were some malformed %s-s and I could not longer watch it in the logs.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e449d7deef67499f42533be4c2109e4cfa3cf0f7:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e561676dd0c22adc289121b449f735be43ae8fcc:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d4b4ce645822910b8ad0e336beef8cd0a62c4c21:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
This should be OK to merge. @psav ?

**Pull request merged**
