### PR TITLE
New CRUD tests for Container Image policies

### PR DESCRIPTION
**Pull request by quarckster**
@psav, @mfalesni please review

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1b5f23120d85154d72e44b6c6b74255d55e0511f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@quarckster Can you `@pytest.mark.tier(2)` the crud tests? While you are in the file, you can do it for the rest of them? Other tests should be tier 3.

**Comment by dajoRH** [comment]
Lint report for commit e2713df0f5e888df87b7443e873930a7c148cbf0:

`cfme/tests/control/test_basic.py`:
- :bangbang: Line 457:1: **E302** *expected 2 blank lines, found 1*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f454da59a747c2a4ac5a95e0a887a95df9ff34ef:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ee4b39873135dc9ec809ea8e18111788bf14a43b:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
