### PR TITLE
Fixed OpenLDAP with new login

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e0567e5f6e433a8d06159a32dcca7badc9557ca2:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
```python
    with user:
        login.login(user)
        assert login.current_full_name() == data["fullname"]
```

shall be the cure. I noticed one weird error then with locating something. But the login itself worked.

**Comment by dajoRH** [comment]
Lint report for commit 2cb5bd7598664766cbd2ddcd9f4db6ab2663efed:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Looks good so far, passed on 5.5

**Pull request merged**
