### PR TITLE
[WIP][NO TEST] Sprout - A couple of updates:

### PR DESCRIPTION
**Pull request by mfalesni**
* Introduce a possibility to kill terminate the pool before it is provisioned.
* UI update
* Renaming works again

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit bb62efafd7d080704ee91a6f2ab9d2e898d38ac1:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3ef209af944f5aed9328cf8cbe5d8167cfcbf4ca:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
Looks good!

**Comment by mfalesni** [comment]
Ok, merging then.

**Pull request merged**
