### PR TITLE
[WIP][NO TEST] Sprout - Socket logging for improved server stability.

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f8a3920bef8ca8ccd047e58cc7ff427f13dfaa67:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav What do you say about this? I checked it from console that it should be working, even practically the same as the original solution.

**Comment by dajoRH** [comment]
Lint report for commit f113ccc3828b1372b382e5ed987bbbfc5f29ae47:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by mfalesni** [comment]
Merging in order to stabilize sprout, will troubleshoot any issues.

**Pull request merged**
